/* ==========================================================================
   View: Backup, restore, cloud sync, data tools
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el;
  function refresh() {
    if (!el) return; const s = ERP.settings.all(); const usage = ERP.db.usage(); const snap = ERP.backup.localSnapshotMeta(); const cs = ERP.cloud ? ERP.cloud.status : 'off'; const pend = ERP.cloud && ERP.cloud.pending ? ERP.cloud.pending() : 0;
    ERP.db.usageAsync().then(x => { const n = $('#bk-usage-sub', el); if (n && x.quotaMB) n.textContent = `${x.usedMB} MB مستخدمة من ${x.quotaMB} MB متاحة (${x.pct}%) · ${usage.docs} سجل`; });
    $('#bk-status', el).innerHTML = `<div class="kpi-grid">${[['database', usage.mode === 'idb' ? 'success' : 'warning', `حجم البيانات (${usage.mode === 'idb' ? 'IndexedDB' : 'localStorage'})`, `${usage.kb >= 1024 ? (usage.kb / 1024).toFixed(1) + ' MB' : usage.kb + ' KB'}`, `<span id="bk-usage-sub">${usage.docs} سجل · ${usage.pct}% من السعة</span>`], ['clock', 'info', 'آخر نسخة يدوية', s.lastManualBackup ? u.relTime(s.lastManualBackup) : 'لم تتم', s.lastManualBackup ? u.fmtDateTime(s.lastManualBackup) : ''], ['rotate', 'success', 'نسخة المتصفح التلقائية', snap ? u.relTime(snap.at) : 'لا توجد', snap ? `(${e(snap.reason)})` : ''], ['cloud', cs === 'online' ? 'success' : cs === 'error' || cs === 'offline' ? 'danger' : 'warning', 'المزامنة السحابية', cs === 'online' ? 'متصل' : cs === 'connecting' ? 'جارٍ الاتصال…' : cs === 'offline' ? 'غير متصل — سيُستأنف تلقائياً' : cs === 'error' ? 'خطأ' : 'غير مفعّلة', `${pend ? `<span class="text-warning">${pend} تغيير بانتظار الرفع</span> · ` : ''}${s.lastCloudSync ? `آخر مزامنة ${u.relTime(s.lastCloudSync)}` : ''}`]].map(k => `<div class="card kpi"><div class="kpi-icon ${k[1]}"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.1rem">${k[3]}</div><div class="text-xs muted">${k[4]}</div></div></div>`).join('')}</div>${usage.pct > 70 ? `<div class="alert alert-warning mt-3"><i class="fas fa-triangle-exclamation"></i> مساحة التخزين تقترب من الحد. نزّل نسخة احتياطية وفعّل المزامنة السحابية أو نظّف السجلات القديمة.</div>` : ''}${usage.mode !== 'idb' ? `<div class="alert alert-info mt-3"><i class="fas fa-circle-info"></i> المتصفح لا يدعم IndexedDB هنا — يعمل النظام على localStorage (سعة ~5 ميجابايت). استخدم Chrome/Edge بدون وضع التصفح الخفي للسعة الكاملة.</div>` : ''}`;
    const counts = ERP.db.KNOWN.map(n => [n, ERP.db.collection(n).count()]).filter(x => x[1]);
    $('#bk-counts', el).innerHTML = counts.map(([n, c]) => `<span class="badge badge-neutral">${e(n)}: <strong class="num">${c}</strong></span>`).join(' ');
  }
  async function restoreFile(mode) {
    const inp = document.createElement('input'); inp.type = 'file'; inp.accept = '.json,application/json';
    inp.onchange = async () => { const f = inp.files[0]; if (!f) return; if (!await ERP.ui.confirm(`${mode === 'replace' ? '<strong class="text-danger">سيتم استبدال كل البيانات الحالية</strong> بمحتوى الملف.' : 'سيتم دمج بيانات الملف مع البيانات الحالية.'}<br>سيتم حفظ نسخة أمان محلية قبل الاستعادة. متابعة؟`, { title: 'استعادة نسخة احتياطية', danger: mode === 'replace', okText: 'استعادة' })) return; const l = ERP.ui.loading('جاري الاستعادة…'); try { const r = await ERP.backup.importFile(f, { mode }); l.close(); ERP.ui.success(r.legacy ? `تم استيراد بيانات النظام القديم: ${r.stats.products} منتج، ${r.stats.sales} فاتورة` : `تمت الاستعادة (${r.cols} جدول)`); setTimeout(() => location.reload(), 1200); } catch (err) { l.close(); ERP.ui.error(err.message); } };
    inp.click();
  }
  async function cleanup() {
    const r = await ERP.ui.form({ title: 'تنظيف السجلات القديمة', icon: 'broom', fields: [{ name: 'i', type: 'html', cols: 2, html: '<div class="alert alert-warning"><i class="fas fa-triangle-exclamation"></i> يحذف سجلات التدقيق والإشعارات وحركات المخزون الأقدم من التاريخ المحدد. الفواتير والقيود لا تُحذف.</div>' }, { name: 'before', label: 'حذف السجلات الأقدم من', type: 'date', value: u.toISODate(u.addDays(new Date(), -180)), required: true }, { name: 'audit', type: 'checkbox', checkLabel: 'سجل التدقيق', value: true }, { name: 'notif', type: 'checkbox', checkLabel: 'الإشعارات', value: true }, { name: 'moves', type: 'checkbox', checkLabel: 'حركات المخزون (تبقى الأرصدة صحيحة)' }], submitText: 'تنظيف' });
    if (!r) return; await ERP.backup.snapshotLocal('pre-cleanup'); let n = 0;
    if (r.audit) n += ERP.db.collection('auditLog').removeWhere(x => u.toISODate(x.at) < r.before);
    if (r.notif) n += ERP.db.collection('notifications').removeWhere(x => u.toISODate(x.at) < r.before);
    if (r.moves) n += ERP.db.collection('stockMoves').removeWhere(x => u.toISODate(x.date) < r.before);
    ERP.audit.log('data.reset', `تنظيف ${n} سجل قبل ${r.before}`); ERP.ui.success(`تم حذف ${n} سجل`); refresh();
  }
  async function resetAll() {
    const c = await ERP.ui.prompt('هذا الإجراء يمسح <strong>كل</strong> البيانات نهائياً (منتجات، فواتير، عملاء، حسابات…). اكتب "حذف" للتأكيد:', { title: 'مسح كل البيانات', placeholder: 'حذف' }); if (c !== 'حذف') return;
    const keepRef = await ERP.ui.confirm('هل تريد الاحتفاظ بالإعدادات والمستخدمين والفئات والحسابات (مسح الحركات فقط)؟', { okText: 'نعم، احتفظ بها', cancelText: 'لا، مسح كل شيء' });
    await ERP.backup.snapshotLocal('pre-reset'); ERP.backup.exportJSON();
    if (keepRef) { ['products', 'stockMoves', 'stocktakes', 'transfers', 'customers', 'suppliers', 'sales', 'purchases', 'payments', 'expenses', 'journal', 'employees', 'attendance', 'payroll', 'advances', 'shifts', 'heldCarts', 'quotations', 'cashMoves', 'notifications', 'auditLog', 'promotions'].forEach(n => ERP.db.collection(n).clear()); Object.keys(ERP.db.getMeta('seq') || {}).forEach(k => ERP.db.setSeq(k, 0)); ERP.audit.log('data.reset', 'مسح الحركات مع الاحتفاظ بالإعدادات'); await ERP.db.flush(); }
    else { await ERP.db.reset(); }
    setTimeout(() => location.reload(), 400);
  }
  async function cloudSetup() {
    const s = ERP.settings.all(); const cfg = s.firebaseConfig || {};
    const r = await ERP.ui.form({ title: 'إعداد المزامنة السحابية (Firebase)', icon: 'cloud', size: 'lg', values: { ...cfg, cloudStoreId: s.cloudStoreId || '' }, fields: [{ name: 'i', type: 'html', cols: 2, html: '<div class="alert alert-info"><i class="fas fa-circle-info"></i> أنشئ مشروعاً على <a href="https://console.firebase.google.com" target="_blank">Firebase Console</a>، فعّل Firestore، ثم انسخ إعدادات الويب هنا. تُرفع البيانات تلقائياً مع كل تغيير، ويمكن استعادتها من أي جهاز آخر بنفس الإعدادات ومعرّف المتجر.</div>' }, { name: 'apiKey', label: 'apiKey', required: true }, { name: 'authDomain', label: 'authDomain' }, { name: 'projectId', label: 'projectId', required: true }, { name: 'storageBucket', label: 'storageBucket' }, { name: 'messagingSenderId', label: 'messagingSenderId' }, { name: 'appId', label: 'appId' }, { name: 'cloudStoreId', label: 'معرّف المتجر (لتمييز أكثر من فرع)', placeholder: 'main-branch' }], submitText: 'حفظ واتصال', onSubmit: async d => { const { cloudStoreId, i, ...fb } = d; ERP.settings.set({ firebaseConfig: fb, cloudStoreId, cloudSync: true }); await (ERP.cloud ? ERP.cloud.connect(fb) : (() => { throw new Error('مكتبة السحابة غير محمّلة'); })()); } });
    if (r) { ERP.ui.success('تم الاتصال بالسحابة'); refresh(); }
  }
  ERP.router.register({
    id: 'backup', title: 'النسخ الاحتياطي والبيانات', icon: 'cloud-arrow-down', section: 'النظام', order: 2, perm: 'backup.manage',
    render(root) {
      el = root;
      root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-cloud-arrow-down"></i> النسخ الاحتياطي والبيانات</h2><div class="desc">حماية بياناتك: تصدير، استعادة، مزامنة سحابية، وأدوات البيانات</div></div></div><div id="bk-status" class="mb-4"></div>
        <div class="grid grid-2 gap-4">
          <div class="card"><div class="card-header"><h3><i class="fas fa-download"></i> تصدير نسخة احتياطية</h3></div><div class="card-body"><p class="text-sm muted mb-3">نزّل نسخة كاملة من كل البيانات. احفظها في مكان آمن (فلاشة / Google Drive) بشكل دوري.</p><div class="flex gap-2 flex-wrap"><button class="btn btn-primary" id="bk-json"><i class="fas fa-file-code"></i> نسخة كاملة (JSON)</button><button class="btn btn-outline" id="bk-xlsx"><i class="fas fa-file-excel"></i> تصدير Excel للقراءة</button></div><div class="text-xs muted mt-3" id="bk-counts"></div></div></div>
          <div class="card"><div class="card-header"><h3><i class="fas fa-upload"></i> استعادة</h3></div><div class="card-body"><p class="text-sm muted mb-3">استعادة من ملف JSON (يدعم أيضاً ملفات النظام القديم). تُحفظ نسخة أمان محلية قبل الاستعادة.</p><div class="flex gap-2 flex-wrap"><button class="btn btn-warning" id="bk-restore"><i class="fas fa-rotate-left"></i> استبدال كامل</button><button class="btn btn-outline" id="bk-merge"><i class="fas fa-code-merge"></i> دمج مع الحالي</button><button class="btn btn-outline" id="bk-local"><i class="fas fa-clock-rotate-left"></i> استعادة نسخة المتصفح</button></div></div></div>
          <div class="card"><div class="card-header"><h3><i class="fas fa-cloud"></i> المزامنة السحابية</h3></div><div class="card-body"><p class="text-sm muted mb-3">ربط النظام بـ Firebase لرفع البيانات تلقائياً والعمل من أكثر من جهاز.</p><div class="flex gap-2 flex-wrap"><button class="btn btn-primary" id="bk-cloud"><i class="fas fa-gear"></i> إعداد / اتصال</button><button class="btn btn-outline" id="bk-push"><i class="fas fa-cloud-arrow-up"></i> رفع كل البيانات</button><button class="btn btn-outline" id="bk-pull"><i class="fas fa-cloud-arrow-down"></i> استعادة من السحابة</button><button class="btn btn-ghost text-danger" id="bk-cloud-off">فصل</button></div></div></div>
          ${ERP.autoBackup ? '<div class="card"><div class="card-header"><h3><i class="fas fa-hard-drive"></i> النسخ التلقائي (مجلد / فلاشة / Google Drive)</h3></div><div class="card-body"><div class="text-sm mb-3" id="bk-auto">…</div><div class="flex gap-2 flex-wrap"><button class="btn btn-primary" id="bk-auto-now"><i class="fas fa-floppy-disk"></i> نسخ الآن</button><button class="btn btn-outline" id="bk-auto-set"><i class="fas fa-gear"></i> الإعدادات</button></div><div class="text-xs muted mt-2">ملف Google Drive هو نفس ملف النسخة الكاملة — نزّله ثم «استبدال كامل».</div></div></div>' : ''}
          <div class="card" style="border-color:var(--danger)"><div class="card-header"><h3><i class="fas fa-triangle-exclamation text-danger"></i> أدوات خطرة</h3></div><div class="card-body"><p class="text-sm muted mb-3">استخدم بحذر — تُحفظ نسخة أمان تلقائياً قبل أي إجراء.</p><div class="flex gap-2 flex-wrap"><button class="btn btn-outline" id="bk-clean"><i class="fas fa-broom"></i> تنظيف السجلات القديمة</button><button class="btn btn-outline" id="bk-recalc"><i class="fas fa-calculator"></i> إعادة احتساب الأرصدة</button><button class="btn btn-soft-primary" id="bk-tests"><i class="fas fa-vial-circle-check"></i> تشغيل اختبارات النظام</button><button class="btn btn-danger" id="bk-reset"><i class="fas fa-bomb"></i> مسح كل البيانات</button></div></div></div>
        </div>`;
      $('#bk-json', root).onclick = () => { ERP.backup.exportJSON(); ERP.ui.success('تم تنزيل النسخة'); refresh(); };
      $('#bk-xlsx', root).onclick = () => { try { ERP.backup.exportExcel(); } catch (err) { ERP.ui.error(err.message); } };
      $('#bk-restore', root).onclick = () => restoreFile('replace'); $('#bk-merge', root).onclick = () => restoreFile('merge');
      $('#bk-local', root).onclick = async () => { const s = ERP.backup.localSnapshotMeta(); if (!s) return ERP.ui.warn('لا توجد نسخة محلية'); if (await ERP.ui.confirm(`استعادة نسخة المتصفح من ${u.fmtDateTime(s.at)} (${e(s.reason)})؟ ستُستبدل البيانات الحالية.`, { danger: true })) { const l = ERP.ui.loading('جاري الاستعادة…'); try { await ERP.backup.restoreLocalSnapshot(); setTimeout(() => location.reload(), 400); } catch (err) { l.close(); ERP.ui.error(err.message); } } };
      $('#bk-tests', root).onclick = async () => { if (!await ERP.ui.confirm('سيتم تشغيل اختبار شامل (بيع، مرتجع، شراء، تحصيل، جرد…) على نسخة مؤقتة من البيانات ثم استعادة بياناتك كما كانت. متابعة؟', { okText: 'تشغيل الاختبارات' })) return; const l = ERP.ui.loading('جاري تشغيل الاختبارات…'); try { const r = await ERP.tests.run(); l.close(); ERP.ui.view(`نتائج الاختبارات — ${r.passed}/${r.total} ناجح`, `<div class="alert ${r.failed ? 'alert-danger' : 'alert-success'} mb-3"><i class="fas fa-${r.failed ? 'triangle-exclamation' : 'circle-check'}"></i> ${r.failed ? `${r.failed} اختبار فشل` : 'كل الاختبارات نجحت'} · ${r.ms} مللي ثانية · التخزين: ${ERP.db.mode()}</div><div class="table-wrap" style="max-height:60vh;overflow:auto"><table class="table table-compact"><tbody>${r.results.map(x => `<tr class="${x.ok ? '' : 'row-danger'}"><td style="width:30px">${x.ok ? '<i class="fas fa-circle-check text-success"></i>' : '<i class="fas fa-circle-xmark text-danger"></i>'}</td><td>${e(x.name)}</td><td class="text-xs muted">${e(x.detail || '')}</td></tr>`).join('')}</tbody></table></div>`, { size: 'lg' }); refresh(); } catch (err) { l.close(); ERP.ui.error(err.message); } };
      if (ERP.autoBackup) { // [autobackup] status + quick actions (settings live in الإعدادات ← النسخ الاحتياطي التلقائي)
        const st = () => ERP.autoBackup.last().then(l => { const x = $('#bk-auto', root); if (!x) return; const s = ERP.settings.all(); const f = (r, on, lbl) => `<div><strong>${lbl}:</strong> ${on ? '' : '<span class="muted">غير مفعّل</span> · '}${!r ? 'لم يتم بعد' : `${r.ok ? '<span class="text-success">نجح</span>' : `<span class="text-danger">${r.unknown ? 'غير مؤكد' : 'فشل'}</span>`} ${u.relTime(r.at)}${r.err ? ` — <span class="text-danger">${e(r.err)}</span>` : ''}`}</div>`; x.innerHTML = f(l.local, s.abEnabled, 'المجلد') + f(l.drive, s.driveEnabled, 'Google Drive'); });
        st(); $('#bk-auto-set', root).onclick = () => ERP.router.go('settings', { sec: 'autobackup' });
        $('#bk-auto-now', root).onclick = async () => { const l = ERP.ui.loading('جاري النسخ…'); try { const s = ERP.settings.all(); const r = await ERP.autoBackup.runLocal('manual', { gesture: true }); const d = s.driveEnabled && s.driveUrl ? await ERP.autoBackup.uploadDrive('manual') : null; l.close(); const bad = [r, d].filter(x => x && !x.ok); bad.length ? ERP.ui.error(bad.map(x => x.err).join(' · ')) : ERP.ui.success(`تم: ${r.where}${d ? ' + Google Drive' : ''}`); } catch (err) { l.close(); ERP.ui.error(err.message); } st(); };
      }
      $('#bk-cloud', root).onclick = cloudSetup;
      $('#bk-push', root).onclick = async () => { const l = ERP.ui.loading('جاري الرفع…'); try { await ERP.cloud.pushAll(); ERP.ui.success('تم الرفع'); } catch (err) { ERP.ui.error(err.message); } l.close(); refresh(); };
      $('#bk-pull', root).onclick = async () => { if (!await ERP.ui.confirm('استعادة البيانات من السحابة واستبدال الحالية؟', { danger: true })) return; const l = ERP.ui.loading('جاري التنزيل…'); try { const r = await ERP.cloud.pullAll(); ERP.ui.success(`تمت الاستعادة (${r.cols} جدول${r.bad ? '، تخطّى ' + r.bad + ' تالف' : ''})`); setTimeout(() => location.reload(), 800); } catch (err) { ERP.ui.error(err.message); } l.close(); };
      $('#bk-cloud-off', root).onclick = () => { ERP.cloud.disconnect(); ERP.settings.set({ cloudSync: false }); refresh(); };
      $('#bk-clean', root).onclick = cleanup; $('#bk-reset', root).onclick = resetAll;
      $('#bk-recalc', root).onclick = async () => { if (!await ERP.ui.confirm('إعادة احتساب أرصدة العملاء والموردين والمخزون من الحركات المسجلة؟')) return; let fixed = 0; ERP.crm.all().forEach(c => { const st = ERP.crm.statement(c.id); const bal = u.round(st.closing); if (Math.abs(bal - u.num(c.balance)) > 0.009) { ERP.db.collection('customers').update(c.id, { balance: bal }, { silent: true }); fixed++; } }); ERP.purchasing.suppliers().forEach(s => { const st = ERP.purchasing.statement(s.id); const bal = u.round(st.closing); if (Math.abs(bal - u.num(s.balance)) > 0.009) { ERP.db.collection('suppliers').update(s.id, { balance: bal }, { silent: true }); fixed++; } }); ERP.db.collection('products').all().forEach(p => { const byWh = {}; ERP.inventory.moves({ productId: p.id }).forEach(m => { byWh[m.warehouseId] = u.round((byWh[m.warehouseId] || 0) + m.qty, 3); }); const total = u.round(u.sum(Object.values(byWh)), 3); if (ERP.inventory.moves({ productId: p.id }).length && Math.abs(total - u.num(p.stock)) > 0.0001) { ERP.db.collection('products').update(p.id, { stock: total, stockByWh: byWh }, { silent: true }); fixed++; } }); ERP.bus.emit('db:change', { collection: 'products', op: 'bulk' }); ERP.audit.log('data.reset', `إعادة احتساب: ${fixed} تصحيح`); ERP.ui.success(`تم — ${fixed} رصيد تم تصحيحه`); };
    },
    onShow() { refresh(); },
  });
  ERP.bus.on('cloud:status', () => { if (ERP.router.current() === 'backup') refresh(); });
})();
