/* ==========================================================================
   View: Branches — identity, consolidated dashboard, inter-branch transfers
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el, tab = 'dash', tTable;

  function switchTab(t) { tab = t; $$('#br-tabs .tab', el).forEach(x => x.classList.toggle('active', x.dataset.t === t)); $$('.tab-pane', el).forEach(x => x.classList.toggle('active', x.dataset.p === t)); refresh(); }
  async function refresh() {
    if (!el) return; const me = ERP.branches.current();
    $('#br-me', el).innerHTML = `<div class="flex items-center gap-3"><div class="avatar lg" style="border-radius:14px"><i class="fas fa-code-branch"></i></div><div><div class="fw-800 text-lg">${e(me.name)} <span class="badge badge-primary num">${e(me.code)}</span></div><div class="text-sm muted">هذا الجهاز يعمل كفرع «${e(me.code)}» — غيّر الكود والاسم من الإعدادات → بيانات المتجر. كل فاتورة وحركة تُختم بكود الفرع.</div></div></div>`;
    if (tab === 'dash') {
      const saved = await ERP.branches.savedKpis(); const mine = ERP.branches.mine(); const list = [mine, ...Object.values(saved).filter(k => k.code !== mine.code)];
      const tot = f => u.sum(list, f);
      $('#br-kpis', el).innerHTML = [['code-branch', 'primary', 'الفروع', list.length], ['sack-dollar', 'success', 'مبيعات اليوم (كل الفروع)', u.fmtMoney(tot(k => k.today.total))], ['calendar', 'info', 'مبيعات الشهر', u.fmtMoney(tot(k => k.month.total))], ['boxes-stacked', 'purple', 'قيمة المخزون', u.fmtMoney(tot(k => k.stockValue))], ['hand-holding-dollar', 'danger', 'مديونيات العملاء', u.fmtMoney(tot(k => k.debtors))], ['wallet', 'warning', 'مصروفات الشهر', u.fmtMoney(tot(k => k.expensesMonth))]].map(k => `<div class="card kpi"><div class="kpi-icon ${k[1]}"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.2rem">${k[3]}</div></div></div>`).join('');
      $('#br-table', el).innerHTML = `<div class="table-wrap"><table class="table"><thead><tr><th>الفرع</th><th class="num">مبيعات اليوم</th><th class="num">فواتير</th><th class="num">مبيعات الشهر</th>${ERP.auth.can('reports.profit') ? '<th class="num">ربح الشهر</th>' : ''}<th class="num">المخزون</th><th class="num">نواقص</th><th class="num">مديونيات</th><th class="num">مصروفات الشهر</th><th>آخر تحديث</th><th></th></tr></thead><tbody>${list.map(k => `<tr class="${k.code === mine.code ? 'row-selected' : ''}"><td><div class="fw-700">${e(k.name)} ${k.code === mine.code ? u.badge('هذا الجهاز', 'primary') : k.source === 'cloud' ? u.badge('سحابة', 'info') : u.badge('ملف', 'neutral')}</div><div class="text-xs muted num">${e(k.code)}${k.openShifts ? ` · ${k.openShifts} وردية مفتوحة` : ''}</div></td><td class="num fw-700">${u.fmtNum(k.today.total)}</td><td class="num">${k.today.count}</td><td class="num">${u.fmtNum(k.month.total)}</td>${ERP.auth.can('reports.profit') ? `<td class="num text-success">${u.fmtNum(k.month.profit)}</td>` : ''}<td class="num">${u.fmtNum(k.stockValue)}</td><td class="num ${k.lowStock ? 'text-warning fw-700' : ''}">${k.lowStock}</td><td class="num ${k.debtors ? 'text-danger' : ''}">${u.fmtNum(k.debtors)}</td><td class="num">${u.fmtNum(k.expensesMonth)}</td><td class="text-xs muted">${k.code === mine.code ? 'الآن' : u.relTime(k.at)}${k.exportedAt ? `<br>نسخة ${u.fmtDateTime(k.exportedAt)}` : ''}</td><td>${k.code !== mine.code ? `<button class="btn btn-icon btn-sm btn-ghost text-danger" data-forget="${e(k.code)}" data-tip="إزالة"><i class="fas fa-xmark"></i></button>` : ''}</td></tr>`).join('')}</tbody><tfoot><tr><td>الإجمالي</td><td class="num">${u.fmtNum(tot(k => k.today.total))}</td><td class="num">${tot(k => k.today.count)}</td><td class="num">${u.fmtNum(tot(k => k.month.total))}</td>${ERP.auth.can('reports.profit') ? `<td class="num">${u.fmtNum(tot(k => k.month.profit))}</td>` : ''}<td class="num">${u.fmtNum(tot(k => k.stockValue))}</td><td class="num">${tot(k => k.lowStock)}</td><td class="num">${u.fmtNum(tot(k => k.debtors))}</td><td class="num">${u.fmtNum(tot(k => k.expensesMonth))}</td><td colspan="2"></td></tr></tfoot></table></div>`;
      if (list.length > 1) ERP.charts.bar('#br-chart', { labels: list.map(k => k.name), series: [{ label: 'مبيعات الشهر', data: list.map(k => u.round(k.month.total)) }, { label: 'قيمة المخزون', data: list.map(k => u.round(k.stockValue)), color: '#7c3aed' }, { label: 'مديونيات', data: list.map(k => u.round(k.debtors)), color: '#dc2626' }] });
      $('#br-chart-wrap', el).classList.toggle('hidden', list.length < 2);
      const top = list.filter(k => k.top && k.top.length);
      $('#br-top', el).innerHTML = top.length ? top.map(k => `<div class="card card-body"><div class="fw-700 mb-2">${e(k.name)}</div>${k.top.map((t, i) => `<div class="list-row"><div class="rank ${['gold', 'silver', 'bronze'][i] || ''}">${i + 1}</div><div class="grow truncate">${e(t.name)}</div><div class="val">${u.fmtNum(t.total)}</div></div>`).join('')}</div>`).join('') : '';
    } else if (tab === 'transfers') {
      tTable.setRows(ERP.branches.transfers());
      const pend = ERP.branches.pendingCloudInbound();
      $('#br-pending', el).innerHTML = pend.length ? `<div class="alert alert-warning mb-3"><i class="fas fa-truck-ramp-box"></i> <strong>${pend.length}</strong> تحويل وارد من السحابة بانتظار الاستلام: ${pend.map(p => `<button class="btn btn-sm btn-primary" data-recv-cloud="${e(p.id)}">${e(p.no)} من ${e(p.fromBranchName || p.fromBranch)} (${p.lines.length} صنف)</button>`).join(' ')}</div>` : '';
    } else if (tab === 'list') {
      const list = ERP.branches.all();
      $('#br-list', el).innerHTML = list.map(b => `<div class="card card-body flex items-center gap-3 mb-2"><div class="avatar" style="border-radius:10px"><i class="fas fa-store"></i></div><div class="flex-1"><div class="fw-700">${e(b.name)} ${b.isSelf ? u.badge('هذا الجهاز', 'primary') : ''}</div><div class="text-xs muted num">${e(b.code)}${b.phone ? ' · ' + e(b.phone) : ''}${b.address ? ' · ' + e(b.address) : ''}</div></div>${!b.isSelf ? `<button class="btn btn-sm btn-ghost" data-edit-br="${b.id}"><i class="fas fa-pen"></i></button><button class="btn btn-sm btn-ghost text-danger" data-del-br="${b.id}"><i class="fas fa-trash"></i></button>` : `<button class="btn btn-sm btn-outline" onclick="ERP.router.go('settings',{sec:'store'})"><i class="fas fa-gear"></i> تعديل من الإعدادات</button>`}</div>`).join('');
    }
  }
  async function branchForm(id = null) {
    if (!ERP.auth.require('settings.manage')) return; // branch identity = system configuration
    const b = id ? ERP.db.collection('branches').get(id) : null;
    const r = await ERP.ui.form({ title: b ? 'تعديل فرع' : 'إضافة فرع', icon: 'code-branch', values: b || {}, fields: [{ name: 'code', label: 'كود الفرع (يُستخدم في التحويلات)', required: true, placeholder: 'ALEX-01', readonly: !!b }, { name: 'name', label: 'اسم الفرع', required: true }, { name: 'phone', label: 'الهاتف', type: 'tel' }, { name: 'address', label: 'العنوان', cols: 2 }], onSubmit: d => ERP.branches.register(b ? { ...d, code: b.code } : d) });
    if (r) { ERP.ui.success('تم'); refresh(); }
  }
  async function sendDialog() {
    if (!ERP.auth.require('inventory.transfer')) return;
    const others = ERP.branches.all().filter(b => !b.isSelf); if (!others.length) { ERP.ui.warn('أضف فرعاً آخر أولاً (تبويب الفروع)'); return switchTab('list'); }
    const P = ERP.db.collection('products'); const whs = ERP.inventory.warehouses(); let lines = [];
    const h = ERP.ui.modal({ title: 'تحويل بضاعة إلى فرع', icon: 'truck-arrow-right', size: 'lg', body: `<div class="form-row cols-2"><div class="form-group"><label>الفرع المستلم</label><select id="bt-to">${others.map(b => `<option value="${e(b.code)}">${e(b.name)} (${e(b.code)})</option>`).join('')}</select></div><div class="form-group"><label>من مخزن</label><select id="bt-wh">${u.options(whs, { selected: ERP.inventory.defaultWh() })}</select></div></div><div class="form-group"><label>إضافة صنف</label><input id="bt-p" placeholder="ابحث أو امسح الباركود…" autocomplete="off"></div><div class="doc-lines" id="bt-lines"></div><div class="form-group mt-3"><label>ملاحظات</label><input id="bt-note"></div><div class="alert alert-info mt-2"><i class="fas fa-circle-info"></i> بعد التنفيذ يُخصم المخزون هنا ويُنزَّل <strong>ملف التحويل</strong>؛ أرسله للفرع المستلم ليستورده من تبويب التحويلات (أو يظهر له في صندوق التحويلات السحابي إذا كانت المزامنة مفعّلة في الفرعين بنفس حساب الشركة).</div>`, footer: `<button class="btn" data-a="c">إلغاء</button><button class="btn btn-primary" data-a="ok"><i class="fas fa-paper-plane"></i> تنفيذ التحويل وتنزيل الملف</button>` });
    const render = () => { const wh = h.$('#bt-wh').value; h.$('#bt-lines').innerHTML = `<div class="doc-line head" style="grid-template-columns:2fr 1fr 1fr 40px"><span>الصنف</span><span>المتاح</span><span>الكمية</span><span></span></div>` + (lines.map((l, i) => { const p = P.get(l.productId); return `<div class="doc-line" style="grid-template-columns:2fr 1fr 1fr 40px"><span>${e(p.name)}</span><span class="num">${u.fmtQty(ERP.inventory.whQty(p, wh))}</span><input type="number" step="any" min="0" value="${l.qty}" data-i="${i}" class="num"><button class="btn btn-icon btn-sm btn-ghost text-danger" data-d="${i}"><i class="fas fa-xmark"></i></button></div>`; }).join('') || '<div class="p-3 text-center muted text-sm">لا أصناف</div>'); };
    render();
    ERP.ui.picker(h.$('#bt-p'), { source: () => P.all().filter(p => p.active !== false && p.stock > 0), sub: p => `${p.code} · مخزون ${u.fmtQty(p.stock)}`, clearOnPick: true, onPick: p => { const ex = lines.find(l => l.productId === p.id); if (ex) ex.qty++; else lines.push({ productId: p.id, qty: 1 }); render(); } });
    h.$('#bt-lines').addEventListener('input', ev => { if (ev.target.dataset.i !== undefined) lines[+ev.target.dataset.i].qty = u.num(ev.target.value); });
    h.$('#bt-lines').addEventListener('click', ev => { const d = ev.target.closest('[data-d]'); if (d) { lines.splice(+d.dataset.d, 1); render(); } });
    h.$('#bt-wh').onchange = render; h.$('[data-a=c]').onclick = () => h.close();
    h.$('[data-a=ok]').onclick = () => { lines = lines.filter(l => l.qty > 0); if (!lines.length) return ERP.ui.warn('أضف أصنافاً'); try { const t = ERP.branches.sendTransfer({ toBranch: h.$('#bt-to').value, lines, note: h.$('#bt-note').value, fromWh: h.$('#bt-wh').value }); ERP.branches.exportTransfer(t.id); h.close(); ERP.ui.success(`تم التحويل ${t.no} وتنزيل الملف`); refresh(); } catch (err) { ERP.ui.error(err.message); } };
  }
  function receiveFile() { const inp = document.createElement('input'); inp.type = 'file'; inp.accept = '.json'; inp.onchange = async () => { const f = inp.files[0]; if (!f) return; try { const d = await ERP.branches.receiveFile(f); ERP.ui.success(`تم استلام ${d.sourceNo}: ${d.lines.length} صنف بقيمة ${u.fmtMoney(d.value)}`); refresh(); } catch (err) { ERP.ui.error(err.message); } }; inp.click(); }
  function importSnapshot() { const inp = document.createElement('input'); inp.type = 'file'; inp.accept = '.json'; inp.onchange = async () => { const f = inp.files[0]; if (!f) return; const l = ERP.ui.loading('جاري تحليل نسخة الفرع…'); try { const k = await ERP.branches.importSnapshotFile(f); l.close(); ERP.ui.success(`تم تحميل بيانات فرع ${k.name}`); refresh(); } catch (err) { l.close(); ERP.ui.error(err.message); } }; inp.click(); }
  function transferDetails(t) { ERP.ui.view(`تحويل ${e(t.no)} ${u.badge(t.direction === 'out' ? 'صادر' : 'وارد', t.direction === 'out' ? 'warning' : 'success')}`, `<div class="detail-grid mb-3"><div class="detail-item"><div class="dl">التاريخ</div><div class="dv num">${u.fmtDateTime(t.date)}</div></div><div class="detail-item"><div class="dl">من</div><div class="dv">${e(t.fromBranchName || t.fromBranch)}</div></div><div class="detail-item"><div class="dl">إلى</div><div class="dv">${e(t.toBranch)}</div></div><div class="detail-item"><div class="dl">القيمة (تكلفة)</div><div class="dv">${u.fmtMoney(t.value)}</div></div>${t.sourceNo ? `<div class="detail-item"><div class="dl">رقم التحويل الأصلي</div><div class="dv num">${e(t.sourceNo)}</div></div>` : ''}${t.note ? `<div class="detail-item"><div class="dl">ملاحظات</div><div class="dv">${e(t.note)}</div></div>` : ''}</div><div class="table-wrap"><table class="table table-compact"><thead><tr><th>الصنف</th><th class="num">الكمية</th><th class="num">التكلفة</th><th class="num">القيمة</th></tr></thead><tbody>${t.lines.map(l => `<tr><td>${e(l.name)}</td><td class="num">${u.fmtQty(l.qty)}</td><td class="num">${u.fmtNum(l.cost)}</td><td class="num">${u.fmtNum(l.qty * l.cost)}</td></tr>`).join('')}</tbody></table></div>`, { footer: `<button class="btn" onclick="this.closest('.modal-backdrop').remove();document.body.classList.remove('modal-open')">إغلاق</button>${t.direction === 'out' ? `<button class="btn btn-primary" onclick="ERP.branches.exportTransfer('${t.id}')"><i class="fas fa-download"></i> تنزيل ملف التحويل</button>` : ''}` }); }

  ERP.views.branches = { refresh, sendDialog };
  ERP.router.register({
    id: 'branches', title: 'الفروع', icon: 'code-branch', section: 'الإدارة', order: 3, perm: ['reports.view', 'inventory.transfer'],
    badge() { const n = ERP.branches.pendingCloudInbound().length; return n ? { text: n, kind: 'danger' } : null; },
    render(root) {
      el = root;
      root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-code-branch"></i> الفروع</h2><div class="desc">لوحة مركزية لكل الفروع، تحويلات بضاعة بين الفروع بملف أو عبر السحابة</div></div><div class="page-actions"><button class="btn btn-outline" id="br-import"><i class="fas fa-file-import"></i> استيراد نسخة فرع</button><button class="btn btn-outline" id="br-cloud"><i class="fas fa-cloud-arrow-down"></i> تحديث من السحابة</button>${ERP.auth.can('inventory.transfer') ? '<button class="btn btn-outline" id="br-recv"><i class="fas fa-file-arrow-down"></i> استلام ملف تحويل</button><button class="btn btn-primary" id="br-send"><i class="fas fa-truck-arrow-right"></i> تحويل إلى فرع</button>' : ''}</div></div>
        <div class="card card-body mb-4" id="br-me"></div>
        <div class="tabs" id="br-tabs"><button class="tab active" data-t="dash"><i class="fas fa-gauge"></i> اللوحة المركزية</button><button class="tab" data-t="transfers"><i class="fas fa-right-left"></i> التحويلات بين الفروع</button><button class="tab" data-t="list"><i class="fas fa-list"></i> قائمة الفروع</button></div>
        <div class="tab-pane active" data-p="dash"><div class="kpi-grid mb-4" id="br-kpis"></div><div id="br-table" class="mb-4"></div><div class="card mb-4" id="br-chart-wrap"><div class="card-header"><h3><i class="fas fa-chart-column"></i> مقارنة الفروع</h3></div><div class="card-body"><div class="chart-box"><canvas id="br-chart"></canvas></div></div></div><div class="grid grid-3 gap-4" id="br-top"></div><div class="alert alert-info mt-4"><i class="fas fa-circle-info"></i> <strong>كيف تجمع بيانات الفروع؟</strong> إما بتفعيل المزامنة السحابية على كل فرع بنفس حساب الشركة السحابي (كل فرع بكود مختلف) ثم «تحديث من السحابة» — أو من الموبايل عبر لوحة المالك owner.html، أو باستيراد ملف النسخة الاحتياطية الذي يصدّره كل فرع يومياً («استيراد نسخة فرع») — يعمل بدون إنترنت.</div></div>
        <div class="tab-pane" data-p="transfers"><div id="br-pending"></div><div id="br-transfers"></div></div>
        <div class="tab-pane" data-p="list">${ERP.auth.can('settings.manage') ? '<div class="flex justify-end mb-3"><button class="btn btn-primary" id="br-add"><i class="fas fa-plus"></i> إضافة فرع</button></div>' : ''}<div id="br-list"></div></div>`;
      tTable = ERP.ui.table({ el: '#br-transfers', rows: [], exportName: 'تحويلات الفروع', defaultSort: { key: 'date', dir: 'desc' }, columns: [{ key: 'no', label: 'الرقم', render: t => `<strong class="num">${e(t.no)}</strong>` }, { key: 'direction', label: 'الاتجاه', render: t => u.badge(t.direction === 'out' ? 'صادر' : 'وارد', t.direction === 'out' ? 'warning' : 'success') }, { key: 'date', label: 'التاريخ', render: t => `<span class="num">${u.fmtDateTime(t.date)}</span>`, text: t => u.fmtDateTime(t.date) }, { id: 'p', label: 'الطرف', render: t => t.direction === 'out' ? `إلى <strong>${e(t.toBranch)}</strong>` : `من <strong>${e(t.fromBranchName || t.fromBranch)}</strong>`, sortable: false, text: t => t.direction === 'out' ? t.toBranch : t.fromBranch }, { id: 'n', label: 'الأصناف', num: true, render: t => t.lines.length, sortable: false, text: t => t.lines.length }, { key: 'value', label: 'القيمة', num: true, render: t => u.fmtNum(t.value) }, { key: 'status', label: 'الحالة', render: t => u.badge(t.status === 'sent' ? 'مُرسَل' : 'مستلم', t.status === 'sent' ? 'info' : 'success') }, { id: 'a', label: '', sortable: false, export: false, render: t => t.direction === 'out' ? `<button class="btn btn-sm btn-ghost" data-exp="${t.id}"><i class="fas fa-download"></i> الملف</button>` : '' }], onRowClick: t => transferDetails(t) });
      $('#br-tabs', root).onclick = ev => { const t = ev.target.closest('.tab'); if (t) switchTab(t.dataset.t); };
      $('#br-import', root).onclick = importSnapshot;
      $('#br-cloud', root).onclick = async () => { const l = ERP.ui.loading('جاري جلب ملخصات الفروع والتحويلات من السحابة…'); try { const r = await ERP.branches.pullCloud(); l.close(); ERP.ui.success(`تم تحديث ${Object.keys(r).length} فرع`); refresh(); } catch (err) { l.close(); ERP.ui.error(err.message); } };
      const sb = $('#br-send', root); if (sb) sb.onclick = sendDialog; const rb = $('#br-recv', root); if (rb) rb.onclick = receiveFile;
      const ba = $('#br-add', root); if (ba) ba.onclick = () => branchForm();
      root.addEventListener('click', async ev => { const f = ev.target.closest('[data-forget]'); if (f) { await ERP.branches.forgetBranchKpis(f.dataset.forget); return refresh(); } const ex = ev.target.closest('[data-exp]'); if (ex) { ev.stopPropagation(); return ERP.branches.exportTransfer(ex.dataset.exp); } const ed = ev.target.closest('[data-edit-br]'); if (ed) return branchForm(ed.dataset.editBr); const dl = ev.target.closest('[data-del-br]'); if (dl && await ERP.ui.confirm('حذف الفرع من القائمة؟', { danger: true })) { try { ERP.branches.remove(dl.dataset.delBr); refresh(); } catch (err) { ERP.ui.error(err.message); } } const rc = ev.target.closest('[data-recv-cloud]'); if (rc) { const p = ERP.branches.pendingCloudInbound().find(x => x.id === rc.dataset.recvCloud); if (p && await ERP.ui.confirm(`استلام ${p.no} (${p.lines.length} صنف) وإدخاله للمخزون؟`)) { try { const d = ERP.branches.receiveTransfer(p); ERP.ui.success(`تم استلام ${d.sourceNo}`); refresh(); } catch (err) { ERP.ui.error(err.message); } } } });
    },
    onShow(root, params) { if (params.tab) switchTab(params.tab); else refresh(); },
  });
})();
