/* ==========================================================================
   View: Customers — CRM, credit, receipts, statements, loyalty
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el, table, filter = '';
  function rows() { let l = ERP.crm.all(); if (filter === 'debtors') l = l.filter(c => c.balance > 0.009); if (filter === 'overdue') { const ids = new Set(ERP.crm.overdue().map(o => o.customer.id)); l = l.filter(c => ids.has(c.id)); } if (filter === 'inactive') l = l.filter(c => c.active === false); if (filter === 'vip') l = l.filter(c => c.group === 'VIP' || c.group === 'مميز'); return l; }
  function refresh() { if (!table) return; table.setRows(rows()); const d = ERP.crm.debtors(); $('#c-kpis', el).innerHTML = [['users', 'primary', 'إجمالي العملاء', u.fmtInt(ERP.crm.active().length)], ['hand-holding-dollar', 'danger', 'إجمالي المديونيات', u.fmtMoney(u.sum(d, 'balance'))], ['user-clock', 'warning', 'عملاء مدينون', u.fmtInt(d.length)], ['clock', 'purple', 'متأخرون', u.fmtInt(ERP.crm.overdue().length)], ['star', 'success', 'نقاط ولاء نشطة', u.fmtInt(u.sum(ERP.crm.all(), 'loyaltyPoints'))]].map(k => `<div class="card kpi"><div class="kpi-icon ${k[1]}"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.2rem">${k[3]}</div></div></div>`).join(''); }

  async function openForm(id = null) {
    if (!ERP.auth.require('customers.manage')) return;
    const c = id ? ERP.crm.get(id) : null; const canCL = ERP.auth.can('customers.credit_limit');
    const r = await ERP.ui.form({ title: c ? `تعديل عميل — ${e(c.name)}` : 'عميل جديد', icon: 'user', size: 'lg', values: c || {}, fields: [
      { name: 'name', label: 'الاسم', required: true }, { name: 'phone', label: 'الهاتف', type: 'tel' }, { name: 'phone2', label: 'هاتف آخر', type: 'tel' }, { name: 'email', label: 'البريد', type: 'email' },
      { name: 'address', label: 'العنوان', cols: 2 }, { name: 'group', label: 'المجموعة', type: 'select', options: ERP.crm.GROUPS.map(g => `<option ${c?.group === g ? 'selected' : ''}>${g}</option>`).join('') },
      ...(canCL ? [{ name: 'creditLimit', label: 'حد الائتمان (0 = بلا حد)', type: 'number', min: 0, step: 'any' }] : []),
      ...(!c ? [{ name: 'openingBalance', label: 'رصيد مديونية افتتاحي', type: 'number', min: 0, step: 'any', help: 'مديونية سابقة قبل استخدام النظام' }] : []),
      { name: 'taxNumber', label: 'الرقم الضريبي' }, { name: 'birthday', label: 'تاريخ الميلاد', type: 'date' }, { name: 'notes', label: 'ملاحظات', type: 'textarea', cols: 2 },
      ...(c && canCL ? [{ name: 'blocked', type: 'checkbox', checkLabel: 'حظر البيع الآجل لهذا العميل' }, { name: 'active', type: 'checkbox', checkLabel: 'نشط' }] : []),
    ], onSubmit: d => { if (!canCL && c) { delete d.creditLimit; } if (c) return ERP.crm.update(id, d); return ERP.crm.create(d); } });
    if (r) ERP.ui.success('تم الحفظ');
  }
  async function receiptDialog(customerId, saleId = null) {
    if (!ERP.auth.require('customers.receipt')) return;
    const c = ERP.crm.get(customerId); const sale = saleId ? ERP.sales.get(saleId) : null;
    const methods = ERP.sales.methods().filter(m => !m.isCredit);
    const r = await ERP.ui.form({ title: `تحصيل من ${e(c.name)}`, icon: 'hand-holding-dollar', fields: [
      { name: 'info', type: 'html', html: `<div class="alert alert-warning"><i class="fas fa-circle-info"></i> الرصيد الحالي: <strong>${u.fmtMoney(c.balance)}</strong>${sale ? ` · متبقي الفاتورة ${e(sale.no)}: <strong>${u.fmtMoney(sale.due)}</strong>` : ''}</div>`, cols: 2 },
      { name: 'amount', label: 'المبلغ', type: 'number', step: 'any', min: 0.01, required: true, value: sale ? sale.due : c.balance }, { name: 'method', label: 'طريقة الدفع', type: 'select', options: methods.map(m => `<option value="${m.id}">${e(m.name)}</option>`).join('') },
      { name: 'date', label: 'التاريخ', type: 'date', value: u.todayISO() }, { name: 'notes', label: 'ملاحظات' },
    ], submitText: 'تحصيل', onSubmit: d => { if (d.amount > c.balance + 0.01 && !confirm(`المبلغ أكبر من المديونية (${u.fmtMoney(c.balance)}). سيصبح للعميل رصيد دائن. متابعة؟`)) return false; return ERP.crm.receivePayment({ customerId, amount: d.amount, method: d.method, notes: d.notes, saleId, date: d.date ? new Date(d.date + 'T' + new Date().toTimeString().slice(0, 8)).toISOString() : null }); } });
    if (r) { ERP.ui.success(`تم تحصيل ${u.fmtMoney(r.amount)}`); const p = await ERP.ui.confirm('طباعة إيصال التحصيل؟', { okText: 'طباعة', cancelText: 'لا' }); if (p) printReceipt(r); }
  }
  function printReceipt(pay) {
    const s = ERP.settings.all(); const c = ERP.crm.get(pay.partyId);
    ERP.print.html(`<div class="receipt"><div class="center"><div class="store">${e(s.storeName)}</div><div class="small">${e(s.phone || '')}</div></div><hr><div class="center" style="font-weight:800">إيصال تحصيل</div><table><tr><td>رقم</td><td class="num" style="text-align:left">${e(pay.no)}</td></tr><tr><td>التاريخ</td><td class="num" style="text-align:left">${u.fmtDateTime(pay.date)}</td></tr><tr><td>العميل</td><td style="text-align:left">${e(pay.partyName)}</td></tr><tr><td>الطريقة</td><td style="text-align:left">${e(ERP.sales.methodName(pay.method))}</td></tr></table><hr><table class="tot"><tr class="grand"><td>المبلغ المحصّل</td><td class="num" style="text-align:left">${u.fmtNum(pay.amount)} ${e(s.currency)}</td></tr><tr><td>الرصيد المتبقي</td><td class="num" style="text-align:left">${u.fmtNum(c ? c.balance : 0)}</td></tr></table><div class="small" style="margin-top:6px">فقط ${u.numToArabicWords(pay.amount)} ${e(s.currency)}</div><hr><div class="center small">${e(pay.notes || '')}<br>${e(s.receiptThanks)}</div></div>`, { title: pay.no, widthMm: 80 });
  }
  function details(id) {
    const c = ERP.crm.get(id); if (!c) return; const st = ERP.crm.stats(id); const stm = ERP.crm.statement(id);
    const hist = ERP.sales.customerHistory(id).slice(0, 50); const canR = ERP.auth.can('customers.receipt'), canM = ERP.auth.can('customers.manage');
    const h = ERP.ui.view(`<div class="flex items-center gap-3"><div class="avatar lg">${e(u.initials(c.name))}</div><div><div>${e(c.name)} ${u.badge(c.group || 'عادي', 'primary')} ${c.blocked ? u.badge('محظور آجل', 'danger') : ''} ${c.active === false ? u.badge('موقوف', 'neutral') : ''}</div><div class="text-sm muted num fw-500">${e(c.code)} · ${e(c.phone || 'بدون هاتف')}</div></div></div>`, `
      <div class="kpi-grid mb-4">${[['hand-holding-dollar', c.balance > 0 ? 'danger' : 'success', 'الرصيد المستحق', u.fmtMoney(c.balance)], ['receipt', 'primary', 'الفواتير', `${st.invoices}`], ['sack-dollar', 'info', 'إجمالي المشتريات', u.fmtMoney(st.total)], ['star', 'warning', 'نقاط الولاء', `${u.fmtInt(c.loyaltyPoints)} (${u.fmtMoney(ERP.crm.pointsValue(c.loyaltyPoints))})`], ['gauge', 'purple', 'حد الائتمان', c.creditLimit ? `${u.fmtMoney(c.creditLimit)} <div class="progress mt-1"><div class="progress-bar ${c.balance / c.creditLimit > .9 ? 'danger' : c.balance / c.creditLimit > .7 ? 'warning' : ''}" style="width:${Math.min(100, u.pct(c.balance, c.creditLimit))}%"></div></div>` : 'بلا حد']].map(k => `<div class="card kpi" style="padding:.8rem 1rem"><div class="kpi-icon ${k[1]}" style="width:42px;height:42px;font-size:1.1rem"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.1rem">${k[3]}</div></div></div>`).join('')}</div>
      ${c.address || c.notes || c.email ? `<div class="detail-grid mb-3">${c.address ? `<div class="detail-item"><div class="dl">العنوان</div><div class="dv">${e(c.address)}</div></div>` : ''}${c.email ? `<div class="detail-item"><div class="dl">البريد</div><div class="dv">${e(c.email)}</div></div>` : ''}${c.notes ? `<div class="detail-item"><div class="dl">ملاحظات</div><div class="dv">${e(c.notes)}</div></div>` : ''}${st.last ? `<div class="detail-item"><div class="dl">آخر شراء</div><div class="dv">${u.relTime(st.last)}</div></div>` : ''}</div>` : ''}
      <div class="tabs"><button class="tab active" data-t="stm">كشف الحساب</button><button class="tab" data-t="inv">الفواتير</button><button class="tab" data-t="items">المنتجات المشتراة</button></div>
      <div class="tab-pane active" data-p="stm"><div class="table-wrap" style="max-height:360px;overflow:auto"><table class="table table-compact"><thead><tr><th>التاريخ</th><th>النوع</th><th>المرجع</th><th class="num">مدين</th><th class="num">دائن</th><th class="num">الرصيد</th></tr></thead><tbody>${stm.opening ? `<tr><td colspan="5">رصيد افتتاحي</td><td class="num">${u.fmtNum(stm.opening)}</td></tr>` : ''}${stm.rows.slice().reverse().map(r => `<tr><td class="num">${u.fmtDate(r.date)}</td><td>${e(r.type)}</td><td class="num">${e(r.ref)}</td><td class="num">${r.debit ? u.fmtNum(r.debit) : ''}</td><td class="num text-success">${r.credit ? u.fmtNum(r.credit) : ''}</td><td class="num fw-700">${u.fmtNum(r.balance)}</td></tr>`).join('') || '<tr><td colspan="6" class="text-center muted">لا حركات</td></tr>'}</tbody></table></div></div>
      <div class="tab-pane" data-p="inv"><div class="table-wrap" style="max-height:360px;overflow:auto"><table class="table table-compact"><thead><tr><th>الرقم</th><th>التاريخ</th><th class="num">الصافي</th><th class="num">المتبقي</th><th>الحالة</th></tr></thead><tbody>${hist.map(s => `<tr class="cursor-pointer" onclick="ERP.views.sales.viewInvoice('${s.id}')"><td class="num">${e(s.no)}${s.type === 'return' ? ' ' + u.badge('مرتجع', 'purple') : ''}</td><td class="num">${u.fmtDate(s.date)}</td><td class="num">${u.fmtNum(s.total)}</td><td class="num text-danger">${s.due ? u.fmtNum(s.due) : ''}</td><td>${u.statusBadge(s.status)}</td></tr>`).join('') || '<tr><td colspan="5" class="text-center muted">لا فواتير</td></tr>'}</tbody></table></div></div>
      <div class="tab-pane" data-p="items">${(() => { const m = {}; hist.filter(s => s.type === 'sale' && s.status !== 'void').forEach(s => s.items.forEach(it => { m[it.name] = m[it.name] || { name: it.name, qty: 0, total: 0, n: 0 }; m[it.name].qty += it.qty; m[it.name].total += it.total; m[it.name].n++; })); const list = u.sortBy(Object.values(m), 'total', 'desc'); return `<div class="table-wrap" style="max-height:360px;overflow:auto"><table class="table table-compact"><thead><tr><th>الصنف</th><th class="num">مرات الشراء</th><th class="num">الكمية</th><th class="num">الإجمالي</th></tr></thead><tbody>${list.map(x => `<tr><td>${e(x.name)}</td><td class="num">${x.n}</td><td class="num">${u.fmtQty(x.qty)}</td><td class="num">${u.fmtNum(x.total)}</td></tr>`).join('') || '<tr><td colspan="4" class="text-center muted">لا مشتريات</td></tr>'}</tbody></table></div>`; })()}</div>`,
      { size: 'xl', footer: `<button class="btn" data-a="close">إغلاق</button><div class="flex-1"></div><button class="btn btn-outline" data-a="stm"><i class="fas fa-print"></i> كشف حساب</button>${c.phone ? `<a class="btn btn-outline" target="_blank" href="https://wa.me/${e(u.normalizeDigits(c.phone).replace(/\D/g, '').replace(/^0/, '20'))}?text=${encodeURIComponent(`مرحباً ${c.name}، نود تذكيركم برصيد مستحق بقيمة ${u.fmtMoney(c.balance)} لدى ${ERP.settings.get('storeName')}. شكراً لتعاونكم.`)}"><i class="fab fa-whatsapp"></i> واتساب</a>` : ''}${ERP.auth.can('pos.use') ? `<button class="btn btn-outline" data-a="pos"><i class="fas fa-cash-register"></i> بيع</button>` : ''}${canR && c.balance > 0 ? `<button class="btn btn-success" data-a="pay"><i class="fas fa-hand-holding-dollar"></i> تحصيل</button>` : ''}${canM ? `<button class="btn btn-primary" data-a="edit"><i class="fas fa-pen"></i> تعديل</button>` : ''}` });
    h.el.querySelector('.tabs').onclick = ev => { const t = ev.target.closest('.tab'); if (!t) return; h.$$('.tab').forEach(x => x.classList.toggle('active', x === t)); h.$$('.tab-pane').forEach(x => x.classList.toggle('active', x.dataset.p === t.dataset.t)); };
    h.$('[data-a=close]').onclick = () => h.close(); h.$('[data-a=stm]').onclick = () => ERP.print.statement({ title: 'كشف حساب عميل', party: c, rows: stm.rows, opening: stm.opening });
    const pb = h.$('[data-a=pos]'); if (pb) pb.onclick = () => { h.close(); ERP.router.go('pos', { customer: id }); };
    const pay = h.$('[data-a=pay]'); if (pay) pay.onclick = () => { h.close(); receiptDialog(id); };
    const ed = h.$('[data-a=edit]'); if (ed) ed.onclick = () => { h.close(); openForm(id); };
  }
  async function remove(id) { const c = ERP.crm.get(id); if (!ERP.auth.require('customers.manage')) return; if (!await ERP.ui.confirm(`حذف العميل <strong>${e(c.name)}</strong>؟`, { danger: true })) return; try { ERP.crm.remove(id); ERP.ui.success('تم'); } catch (err) { ERP.ui.error(err.message); } }

  ERP.views.customers = { openForm, receiptDialog, details, remove, printReceipt };
  ERP.router.register({
    id: 'customers', title: 'العملاء', icon: 'users', section: 'الأطراف', order: 1, perm: 'customers.view',
    badge() { const n = ERP.crm.overdue().length; return n ? { text: n, kind: 'danger' } : null; },
    render(root) {
      el = root; const canM = ERP.auth.can('customers.manage'), canR = ERP.auth.can('customers.receipt');
      root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-users"></i> العملاء</h2><div class="desc">قاعدة العملاء، المديونيات، التحصيل ونقاط الولاء</div></div><div class="page-actions"><button class="btn btn-outline" id="c-aging"><i class="fas fa-hourglass-half"></i> أعمار الديون</button><button class="btn btn-outline" id="c-print"><i class="fas fa-print"></i> تقرير المديونيات</button>${canM ? '<button class="btn btn-primary" id="c-add"><i class="fas fa-user-plus"></i> عميل جديد</button>' : ''}</div></div>
        <div class="kpi-grid mb-4" id="c-kpis"></div><div id="c-table"></div>`;
      table = ERP.ui.table({ el: '#c-table', rows: [], exportName: 'العملاء', defaultSort: { key: 'balance', dir: 'desc' }, toolbarExtra: `<select id="c-f" style="min-width:150px"><option value="">كل العملاء</option><option value="debtors">المدينون</option><option value="overdue">المتأخرون</option><option value="vip">VIP / مميز</option><option value="inactive">موقوفون</option></select>`, columns: [
        { key: 'name', label: 'العميل', render: (c, t) => `<div class="flex items-center gap-2"><div class="avatar sm">${e(u.initials(c.name))}</div><div><div class="fw-600">${u.highlight(c.name, t)} ${c.blocked ? '<i class="fas fa-ban text-danger text-xs"></i>' : ''}</div><div class="text-xs muted num">${u.highlight(c.code, t)}</div></div></div>`, text: c => c.name + ' ' + c.code },
        { key: 'phone', label: 'الهاتف', render: (c, t) => `<span class="num">${u.highlight(c.phone || '—', t)}</span>` },
        { key: 'group', label: 'المجموعة', render: c => u.badge(c.group || 'عادي', 'neutral') },
        { key: 'balance', label: 'الرصيد المستحق', num: true, render: c => c.balance > 0 ? `<strong class="text-danger">${u.fmtNum(c.balance)}</strong>` : c.balance < 0 ? `<span class="text-success">(${u.fmtNum(-c.balance)})</span>` : '—', footer: r => `<span class="text-danger">${u.fmtMoney(u.sum(r.filter(c => c.balance > 0), 'balance'))}</span>` },
        { key: 'creditLimit', label: 'حد الائتمان', num: true, render: c => c.creditLimit ? `${u.fmtNum(c.creditLimit)} <div class="progress mt-1" style="width:70px"><div class="progress-bar ${c.balance / c.creditLimit > .9 ? 'danger' : ''}" style="width:${Math.min(100, u.pct(c.balance, c.creditLimit))}%"></div></div>` : '<span class="muted">—</span>' },
        { key: 'loyaltyPoints', label: 'النقاط', num: true, render: c => c.loyaltyPoints ? `<i class="fas fa-star text-warning text-xs"></i> ${u.fmtInt(c.loyaltyPoints)}` : '—' },
        { key: 'totalPurchases', label: 'المشتريات', num: true, render: c => u.fmtNum(c.totalPurchases || 0) },
        { key: 'lastPurchaseAt', label: 'آخر شراء', render: c => `<span class="text-xs muted">${c.lastPurchaseAt ? u.relTime(c.lastPurchaseAt) : '—'}</span>` },
        { id: 'a', label: '', sortable: false, export: false, class: 'actions', render: c => `<button class="btn btn-icon btn-sm btn-ghost" data-a="view" data-id="${c.id}"><i class="fas fa-eye"></i></button>${canR && c.balance > 0 ? `<button class="btn btn-icon btn-sm btn-soft-success" data-a="pay" data-id="${c.id}" data-tip="تحصيل"><i class="fas fa-hand-holding-dollar"></i></button>` : ''}${canM ? `<button class="btn btn-icon btn-sm btn-ghost" data-a="edit" data-id="${c.id}"><i class="fas fa-pen"></i></button><button class="btn btn-icon btn-sm btn-ghost text-danger" data-a="del" data-id="${c.id}"><i class="fas fa-trash"></i></button>` : ''}` },
      ], rowClass: c => c.active === false ? 'muted' : '', onRowClick: c => details(c.id) });
      $('#c-f', root).onchange = ev => { filter = ev.target.value; refresh(); };
      root.addEventListener('click', ev => { const b = ev.target.closest('[data-a][data-id]'); if (!b) return; ev.stopPropagation(); const { a, id } = b.dataset; if (a === 'view') details(id); if (a === 'edit') openForm(id); if (a === 'del') remove(id); if (a === 'pay') receiptDialog(id); });
      if (canM) $('#c-add', root).onclick = () => openForm();
      $('#c-print', root).onclick = () => { const d = u.sortBy(ERP.crm.debtors(), 'balance', 'desc'); ERP.print.table({ title: 'تقرير مديونيات العملاء', columns: [{ label: 'الكود' }, { label: 'العميل' }, { label: 'الهاتف' }, { label: 'الرصيد', num: true }, { label: 'حد الائتمان', num: true }, { label: 'آخر شراء' }], rows: d.map(c => [c.code, c.name, c.phone || '', u.fmtNum(c.balance), c.creditLimit ? u.fmtNum(c.creditLimit) : '—', c.lastPurchaseAt ? u.fmtDate(c.lastPurchaseAt) : '—']), summary: [{ label: 'عدد المدينين', value: d.length }, { label: 'إجمالي المديونيات', value: u.fmtMoney(u.sum(d, 'balance')) }] }); };
      $('#c-aging', root).onclick = () => { const a = ERP.reports.debtorsAging(); ERP.ui.view('أعمار الديون', `<div class="kpi-grid mb-4">${a.buckets.map((b, i) => `<div class="card kpi" style="padding:.8rem 1rem"><div class="kpi-icon ${['success', 'info', 'warning', 'danger'][i]}" style="width:42px;height:42px"><i class="fas fa-hourglass-${['start', 'half', 'half', 'end'][i]}"></i></div><div class="kpi-body"><div class="kpi-label">${b.label}</div><div class="kpi-value" style="font-size:1.1rem">${u.fmtMoney(b.total)}</div><div class="text-xs muted">${b.count} عميل</div></div></div>`).join('')}</div><div class="table-wrap" style="max-height:400px;overflow:auto"><table class="table table-compact"><thead><tr><th>العميل</th><th class="num">الرصيد</th><th class="num">أيام</th><th>الفئة</th><th class="num">فواتير مفتوحة</th></tr></thead><tbody>${a.rows.map(r => `<tr class="cursor-pointer" onclick="ERP.views.customers.details('${r.customer.id}')"><td>${e(r.customer.name)}</td><td class="num text-danger">${u.fmtNum(r.balance)}</td><td class="num">${r.days}</td><td>${u.badge(r.bucket, r.days > 90 ? 'danger' : r.days > 60 ? 'warning' : r.days > 30 ? 'info' : 'success')}</td><td class="num">${r.invoices}</td></tr>`).join('')}</tbody></table></div>`, { size: 'lg' }); };
    },
    onShow(root, params) { if (params.filter) { filter = params.filter; $('#c-f', root).value = filter; } refresh(); if (params.id) details(params.id); },
  });
  ERP.bus.on('db:change', u.debounce(ev => { if (table && ERP.router.current() === 'customers' && ['customers', 'sales', 'payments'].includes(ev?.collection)) refresh(); }, 250));
})();
