/* ==========================================================================
   View: Gift cards / prepaid balance
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el, table;
  const KIND = { active: 'success', used: 'neutral', disabled: 'danger' }; const LBL = { active: 'نشطة', used: 'مستهلكة', disabled: 'معطلة' };
  function refresh() { if (!table) return; const all = ERP.giftcards.all(); table.setRows(all); const act = all.filter(c => c.status === 'active'); $('#gc-kpis', el).innerHTML = [['gift', 'primary', 'بطاقات نشطة', act.length], ['coins', 'warning', 'رصيد مستحق (التزام)', u.fmtMoney(u.sum(act, 'balance'))], ['sack-dollar', 'success', 'إجمالي المبيع', u.fmtMoney(u.sum(all, 'initial'))], ['circle-check', 'info', 'مُستهلَك', u.fmtMoney(u.sum(all, c => c.initial - c.balance))]].map(k => `<div class="card kpi"><div class="kpi-icon ${k[1]}"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.2rem">${k[3]}</div></div></div>`).join(''); }
  async function issue() {
    if (!ERP.auth.require('pos.use')) return;
    const methods = ERP.sales.methods().filter(m => !m.isCredit && !m.isGift);
    const r = await ERP.ui.form({ title: 'بيع بطاقة هدايا / شحن رصيد', icon: 'gift', fields: [{ name: 'amount', label: 'قيمة البطاقة', type: 'number', step: 'any', min: 1, required: true }, { name: 'method', label: 'طريقة الدفع', type: 'select', options: methods.map(m => `<option value="${m.id}">${e(m.name)}</option>`).join('') }, { name: 'customerId', label: 'العميل (اختياري)', type: 'select', options: u.options(ERP.crm.active(), { empty: '— بدون —' }) }, { name: 'expiryMonths', label: 'الصلاحية (شهر)', type: 'number', min: 0, value: 12 }, { name: 'code', label: 'رقم البطاقة (اختياري — يُولَّد تلقائياً)', placeholder: 'GCXXXX0000' }, { name: 'note', label: 'ملاحظات', cols: 2 }], submitText: 'إصدار', onSubmit: d => ERP.giftcards.issue(d) });
    if (r) { ERP.ui.success(`تم إصدار البطاقة ${r.code}`); printCard(r); refresh(); }
  }
  function printCard(c) { const s = ERP.settings.all(); ERP.print.html(`<div class="receipt"><div class="center"><div class="store">${e(s.storeName)}</div><div style="font-weight:800;font-size:14px;margin-top:6px">🎁 بطاقة هدايا</div></div><hr><div class="center" style="font-size:22px;font-weight:800;letter-spacing:2px;font-family:monospace">${e(c.code)}</div>${ERP.print.barcodeSvg(c.code, { height: 40, width: 1.6 })}<hr><table><tr><td>القيمة</td><td class="num" style="text-align:left">${u.fmtMoney(c.initial)}</td></tr><tr><td>الرصيد</td><td class="num" style="text-align:left">${u.fmtMoney(c.balance)}</td></tr>${c.expiry ? `<tr><td>صالحة حتى</td><td class="num" style="text-align:left">${u.fmtDate(c.expiry)}</td></tr>` : ''}${c.customerName ? `<tr><td>لصاحبها</td><td style="text-align:left">${e(c.customerName)}</td></tr>` : ''}</table><hr><div class="center small">قدّم هذه البطاقة عند الدفع في ${e(s.storeName)}<br>${e(s.receiptThanks)}</div></div>`, { title: c.code, widthMm: 80 }); }
  ERP.views.giftcards = { issue, printCard, refresh };
  ERP.router.register({
    id: 'giftcards', title: 'بطاقات الهدايا', icon: 'gift', section: 'الأطراف', order: 4, perm: 'pos.use',
    render(root) {
      el = root;
      root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-gift"></i> بطاقات الهدايا والرصيد المسبق</h2><div class="desc">تُباع كبطاقة أو رصيد للعميل وتُستخدم كطريقة دفع في نقطة البيع (طريقة الدفع: بطاقة هدايا)</div></div><div class="page-actions"><button class="btn btn-primary" id="gc-add"><i class="fas fa-plus"></i> بيع بطاقة</button></div></div><div class="kpi-grid mb-4" id="gc-kpis"></div><div id="gc-table"></div>`;
      table = ERP.ui.table({ el: '#gc-table', rows: [], exportName: 'بطاقات الهدايا', defaultSort: { key: 'createdAt', dir: 'desc' }, columns: [{ key: 'code', label: 'الرقم', render: (c, t) => `<strong class="num">${u.highlight(c.code, t)}</strong>` }, { key: 'createdAt', label: 'الإصدار', render: c => `<span class="num text-sm">${u.fmtDate(c.createdAt)}</span>`, text: c => u.fmtDate(c.createdAt) }, { key: 'customerName', label: 'العميل', render: c => e(c.customerName || '—') }, { key: 'initial', label: 'القيمة', num: true, render: c => u.fmtNum(c.initial) }, { key: 'balance', label: 'الرصيد', num: true, render: c => `<strong class="${c.balance > 0 ? 'text-success' : 'muted'}">${u.fmtNum(c.balance)}</strong>`, footer: r => u.fmtMoney(u.sum(r.filter(c => c.status === 'active'), 'balance')) }, { key: 'expiry', label: 'الصلاحية', render: c => c.expiry ? `<span class="num ${c.expiry < u.todayISO() ? 'text-danger' : ''}">${u.fmtDate(c.expiry)}</span>` : '—' }, { key: 'status', label: 'الحالة', render: c => u.badge(LBL[c.status] || c.status, KIND[c.status] || 'neutral') }, { id: 'a', label: '', sortable: false, export: false, class: 'actions', render: c => `<button class="btn btn-icon btn-sm btn-ghost" data-p="${c.id}" data-tip="طباعة"><i class="fas fa-print"></i></button>${c.status !== 'disabled' ? `<button class="btn btn-icon btn-sm btn-ghost" data-t="${c.id}" data-tip="شحن"><i class="fas fa-plus"></i></button><button class="btn btn-icon btn-sm btn-ghost text-danger" data-x="${c.id}" data-tip="تعطيل"><i class="fas fa-ban"></i></button>` : ''}` }], onRowClick: c => ERP.ui.view(`بطاقة ${e(c.code)}`, `<div class="detail-grid mb-3"><div class="detail-item"><div class="dl">القيمة</div><div class="dv">${u.fmtMoney(c.initial)}</div></div><div class="detail-item"><div class="dl">الرصيد</div><div class="dv text-success">${u.fmtMoney(c.balance)}</div></div><div class="detail-item"><div class="dl">الحالة</div><div class="dv">${u.badge(LBL[c.status], KIND[c.status])}</div></div></div><div class="timeline">${(c.history || []).slice().reverse().map(h => `<div class="timeline-item ${h.amount < 0 ? 'warning' : 'success'}"><div class="text-sm"><strong>${{ issue: 'إصدار', topup: 'شحن', redeem: 'استخدام', refund: 'استرداد' }[h.type] || h.type}</strong> <span class="num">${u.fmtNum(h.amount)}</span> ${h.ref ? `<span class="muted num">${e(h.ref)}</span>` : ''}</div><div class="text-xs muted">${u.fmtDateTime(h.at)}</div></div>`).join('')}</div>`) });
      $('#gc-add', root).onclick = issue;
      root.addEventListener('click', async ev => { const p = ev.target.closest('[data-p]'); if (p) { ev.stopPropagation(); return printCard(ERP.db.collection('giftCards').get(p.dataset.p)); } const t = ev.target.closest('[data-t]'); if (t) { ev.stopPropagation(); const amt = await ERP.ui.prompt('قيمة الشحن', { title: 'شحن البطاقة', type: 'number' }); if (amt) { try { ERP.giftcards.topUp(t.dataset.t, amt); ERP.ui.success('تم الشحن'); refresh(); } catch (err) { ERP.ui.error(err.message); } } return; } const x = ev.target.closest('[data-x]'); if (x) { ev.stopPropagation(); if (await ERP.ui.confirm('تعطيل البطاقة؟ لن تُقبل في الدفع.', { danger: true })) { ERP.giftcards.deactivate(x.dataset.x); refresh(); } } });
    },
    onShow() { refresh(); },
  });
  ERP.bus.on('db:change', u.debounce(ev => { if (table && ERP.router.current() === 'giftcards' && ev?.collection === 'giftCards') refresh(); }, 250));
})();
