/* ==========================================================================
   View: HR — employees, attendance, advances, payroll, performance
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el, tab = 'emp', tables = {}, month = u.monthKey(new Date());
  function switchTab(t) { tab = t; $$('#hr-tabs .tab', el).forEach(x => x.classList.toggle('active', x.dataset.t === t)); $$('.tab-pane', el).forEach(x => x.classList.toggle('active', x.dataset.p === t)); refresh(); }
  function refresh() {
    if (!el) return; month = $('#hr-month', el).value || month;
    const emps = ERP.hr.employees();
    $('#hr-kpis', el).innerHTML = [['users', 'primary', 'الموظفون', emps.filter(x => x.active !== false).length], ['money-bill', 'success', 'إجمالي الرواتب الشهرية', u.fmtMoney(u.sum(emps.filter(x => x.active !== false), 'salary'))], ['hand-holding-dollar', 'warning', 'سلف مفتوحة', u.fmtMoney(u.sum(ERP.db.collection('advances').all(), 'remaining'))], ['calendar-check', 'info', `حضور اليوم`, `${ERP.hr.attendance({ from: u.todayISO(), to: u.todayISO() }).filter(a => ['present', 'late'].includes(a.status)).length}/${emps.filter(x => x.active !== false).length}`]].map(k => `<div class="card kpi"><div class="kpi-icon ${k[1]}"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.2rem">${k[3]}</div></div></div>`).join('');
    if (tab === 'emp') tables.emp.setRows(emps);
    else if (tab === 'att') { const d = $('#hr-att-date', el).value || u.todayISO(); const recs = u.keyBy(ERP.hr.attendance({ from: d, to: d }), 'employeeId'); tables.att.setRows(emps.filter(x => x.active !== false).map(x => ({ ...x, rec: recs[x.id] || null }))); }
    else if (tab === 'pay') { const paid = u.keyBy(ERP.hr.payroll({ month }), 'employeeId'); tables.pay.setRows(emps.filter(x => x.active !== false).map(x => ({ ...x, pr: paid[x.id] || null, calc: paid[x.id] ? null : ERP.hr.computeSalary(x.id, month) }))); }
    else if (tab === 'adv') tables.adv.setRows(u.sortBy(ERP.db.collection('advances').all(), 'date', 'desc'));
    else if (tab === 'perf') { const P = ERP.reports.period('month'); tables.perf.setRows(ERP.hr.performance(P.from, P.to).map(x => ({ id: x.userId, ...x }))); }
  }
  async function openForm(id = null) {
    if (!ERP.auth.require('hr.manage')) return;
    const x = id ? ERP.hr.get(id) : null; const users = ERP.auth.users();
    const r = await ERP.ui.form({ title: x ? `تعديل موظف — ${e(x.name)}` : 'موظف جديد', icon: 'id-card', size: 'lg', values: x || { hireDate: u.todayISO(), shiftStart: '09:00', shiftEnd: '17:00', dailyHours: 8 }, fields: [{ name: 'name', label: 'الاسم', required: true }, { name: 'job', label: 'الوظيفة', type: 'select', options: ERP.hr.JOBS.map(j => `<option ${x?.job === j ? 'selected' : ''}>${j}</option>`).join('') }, { name: 'phone', label: 'الهاتف', type: 'tel' }, { name: 'nationalId', label: 'الرقم القومي' }, { name: 'salary', label: 'الراتب الشهري', type: 'number', step: 'any', min: 0, required: true }, { name: 'hireDate', label: 'تاريخ التعيين', type: 'date' }, { name: 'shiftStart', label: 'بداية الدوام', type: 'time' }, { name: 'shiftEnd', label: 'نهاية الدوام', type: 'time' }, { name: 'dailyHours', label: 'ساعات العمل اليومية', type: 'number', min: 1, max: 16 }, { name: 'userId', label: 'حساب المستخدم المرتبط', type: 'select', options: u.options(users, { selected: x?.userId, empty: '— بدون —' }) }, { name: 'address', label: 'العنوان', cols: 2 }, { name: 'notes', label: 'ملاحظات', type: 'textarea', cols: 2 }, ...(x ? [{ name: 'active', type: 'checkbox', checkLabel: 'على رأس العمل' }] : [])], onSubmit: d => x ? ERP.hr.update(id, d) : ERP.hr.create(d) });
    if (r) ERP.ui.success('تم الحفظ');
  }
  async function advance(employeeId) { if (!ERP.auth.require('hr.manage')) return; const emp = ERP.hr.get(employeeId); const r = await ERP.ui.form({ title: `سلفة لـ ${e(emp.name)}`, icon: 'hand-holding-dollar', fields: [{ name: 'i', type: 'html', cols: 2, html: `<div class="alert alert-info"><i class="fas fa-circle-info"></i> الراتب ${u.fmtMoney(emp.salary)} · سلف مفتوحة ${u.fmtMoney(u.sum(ERP.hr.openAdvances(employeeId), 'remaining'))}</div>` }, { name: 'amount', label: 'المبلغ', type: 'number', step: 'any', min: 1, required: true }, { name: 'method', label: 'طريقة الصرف', type: 'select', options: ERP.sales.methods().filter(m => !m.isCredit).map(m => `<option value="${m.id}">${e(m.name)}</option>`).join('') }, { name: 'notes', label: 'ملاحظات', cols: 2 }], submitText: 'صرف', onSubmit: d => ERP.hr.giveAdvance({ employeeId, ...d }) }); if (r) ERP.ui.success('تم صرف السلفة'); }
  async function payDialog(employeeId) {
    if (!ERP.auth.require('hr.manage')) return;
    const emp = ERP.hr.get(employeeId); let calc = ERP.hr.computeSalary(employeeId, month);
    const h = ERP.ui.modal({ title: `صرف راتب ${e(emp.name)} — ${u.fmtMonth(month + '-01')}`, icon: 'money-check-dollar', size: 'lg', body: `<div class="form-row cols-3"><div class="form-group"><label>مكافآت / حوافز</label><input type="number" step="any" min="0" id="pr-bonus" value="0"></div><div class="form-group"><label>ساعات إضافية</label><input type="number" step="any" min="0" id="pr-ot" value="0"></div><div class="form-group"><label>خصومات أخرى</label><input type="number" step="any" min="0" id="pr-ded" value="0"></div><div class="form-group"><label>أيام غياب (من الحضور: ${calc.attendance.absent})</label><input type="number" min="0" id="pr-abs" value="${calc.attendance.absent}"></div><div class="form-group"><label>طريقة الصرف</label><select id="pr-method">${ERP.sales.methods().filter(m => !m.isCredit).map(m => `<option value="${m.id}">${e(m.name)}</option>`).join('')}</select></div><div class="form-group"><label class="checkbox mt-4"><input type="checkbox" id="pr-adv" checked> خصم السلف المفتوحة</label></div></div><div class="card card-body" id="pr-sum"></div>`, footer: `<button class="btn" data-a="c">إلغاء</button><button class="btn btn-success" data-a="ok"><i class="fas fa-check"></i> صرف الراتب</button>` });
    const upd = () => { calc = ERP.hr.computeSalary(employeeId, month, { bonus: h.$('#pr-bonus').value, overtimeHours: h.$('#pr-ot').value, deductions: h.$('#pr-ded').value, absentDays: u.num(h.$('#pr-abs').value), deductAdvances: h.$('#pr-adv').checked }); h.$('#pr-sum').innerHTML = `<div class="tot-row"><span>الراتب الأساسي</span><span class="val">${u.fmtNum(calc.base)}</span></div><div class="tot-row"><span>مكافآت</span><span class="val text-success">+${u.fmtNum(calc.bonus)}</span></div><div class="tot-row"><span>إضافي (${calc.overtimeHours} ساعة × 1.5)</span><span class="val text-success">+${u.fmtNum(calc.overtime)}</span></div><div class="tot-row"><span>خصم غياب (${calc.absentDays} يوم)</span><span class="val text-danger">-${u.fmtNum(calc.absentDeduction)}</span></div><div class="tot-row"><span>خصومات أخرى</span><span class="val text-danger">-${u.fmtNum(calc.otherDeductions)}</span></div><div class="tot-row"><span>سلف مستردة</span><span class="val text-danger">-${u.fmtNum(calc.advancesDeducted)}</span></div><div class="tot-row grand"><span>صافي الراتب</span><span class="val">${u.fmtMoney(calc.net)}</span></div>`; };
    upd(); h.body.addEventListener('input', upd); h.body.addEventListener('change', upd);
    h.$('[data-a=c]').onclick = () => h.close();
    h.$('[data-a=ok]').onclick = () => { try { const pr = ERP.hr.paySalary(calc, { method: h.$('#pr-method').value }); h.close(); ERP.ui.success(`تم صرف ${u.fmtMoney(pr.net)}`); printSlip(pr); } catch (err) { ERP.ui.error(err.message); } };
  }
  function printSlip(pr) { const s = ERP.settings.all(); ERP.print.html(`<div class="a4" style="min-height:auto"><div class="doc-header">${ERP.print.storeHeader()}<div class="doc-title"><h2>قسيمة راتب</h2><div class="doc-no">${e(u.fmtMonth(pr.month + '-01'))}</div></div></div><div class="doc-meta"><div class="box"><h4>الموظف</h4><p><strong>${e(pr.employeeName)}</strong></p></div><div class="box"><h4>تاريخ الصرف</h4><p class="num">${u.fmtDateTime(pr.paidAt)}</p></div></div><table class="doc-table"><tr><td>الراتب الأساسي</td><td class="num">${u.fmtNum(pr.base)}</td></tr><tr><td>مكافآت</td><td class="num">${u.fmtNum(pr.bonus)}</td></tr><tr><td>إضافي</td><td class="num">${u.fmtNum(pr.overtime)}</td></tr><tr><td>خصم غياب (${pr.absentDays} يوم)</td><td class="num">-${u.fmtNum(pr.absentDeduction)}</td></tr><tr><td>خصومات أخرى</td><td class="num">-${u.fmtNum(pr.otherDeductions)}</td></tr><tr><td>سلف مستردة</td><td class="num">-${u.fmtNum(pr.advancesDeducted)}</td></tr><tfoot><tr><td>صافي الراتب</td><td class="num">${u.fmtNum(pr.net)} ${e(s.currency)}</td></tr></tfoot></table><p class="muted" style="margin-top:8px">فقط ${u.numToArabicWords(pr.net)} ${e(s.currency)}</p><div class="doc-sign"><div>المحاسب</div><div>الموظف</div><div>المدير</div></div></div>`, { title: 'قسيمة راتب' }); }
  function empDetails(id) { const x = ERP.hr.get(id); const summ = ERP.hr.monthSummary(id, month); const adv = ERP.hr.advances(id); const pr = ERP.hr.payroll().filter(p => p.employeeId === id); ERP.ui.view(`<div class="flex items-center gap-3"><div class="avatar lg">${e(u.initials(x.name))}</div><div>${e(x.name)} ${u.badge(x.job, 'primary')} ${x.active === false ? u.badge('غير نشط', 'neutral') : ''}<div class="text-sm muted num fw-500">${e(x.code)} · ${e(x.phone || '')} · منذ ${u.fmtDate(x.hireDate)}</div></div></div>`, `<div class="kpi-grid mb-4">${[['money-bill', 'success', 'الراتب', u.fmtMoney(x.salary)], ['calendar-check', 'primary', `حضور ${u.fmtMonth(month + '-01')}`, `${summ.present + summ.late} يوم`], ['clock', 'warning', 'تأخير', `${summ.late} يوم`], ['calendar-xmark', 'danger', 'غياب', `${summ.absent} يوم`], ['hand-holding-dollar', 'purple', 'سلف مفتوحة', u.fmtMoney(u.sum(adv.filter(a => a.remaining > 0), 'remaining'))]].map(k => `<div class="card kpi" style="padding:.8rem 1rem"><div class="kpi-icon ${k[1]}" style="width:42px;height:42px"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.1rem">${k[3]}</div></div></div>`).join('')}</div><h4 class="mb-2">سجل الرواتب</h4><div class="table-wrap mb-4"><table class="table table-compact"><thead><tr><th>الشهر</th><th class="num">الأساسي</th><th class="num">مكافآت</th><th class="num">خصومات</th><th class="num">الصافي</th><th>الصرف</th></tr></thead><tbody>${u.sortBy(pr, 'month', 'desc').map(p => `<tr><td>${u.fmtMonth(p.month + '-01')}</td><td class="num">${u.fmtNum(p.base)}</td><td class="num">${u.fmtNum(p.bonus + p.overtime)}</td><td class="num">${u.fmtNum(p.deductions + p.advancesDeducted)}</td><td class="num fw-700">${u.fmtNum(p.net)}</td><td class="num text-xs">${u.fmtDate(p.paidAt)}</td></tr>`).join('') || '<tr><td colspan="6" class="text-center muted">لا رواتب</td></tr>'}</tbody></table></div><h4 class="mb-2">السلف</h4><div class="table-wrap"><table class="table table-compact"><thead><tr><th>التاريخ</th><th class="num">المبلغ</th><th class="num">المتبقي</th><th>الحالة</th><th>ملاحظات</th></tr></thead><tbody>${adv.map(a => `<tr><td class="num">${u.fmtDate(a.date)}</td><td class="num">${u.fmtNum(a.amount)}</td><td class="num">${u.fmtNum(a.remaining)}</td><td>${u.badge(a.status === 'settled' ? 'مسددة' : 'مفتوحة', a.status === 'settled' ? 'success' : 'warning')}</td><td class="text-sm">${e(a.notes || '')}</td></tr>`).join('') || '<tr><td colspan="5" class="text-center muted">لا سلف</td></tr>'}</tbody></table></div>`, { size: 'lg' }); }

  ERP.views.hr = { openForm, advance, payDialog, empDetails };
  ERP.router.register({
    id: 'hr', title: 'الموظفون', icon: 'id-card', section: 'الإدارة', order: 1, perm: 'hr.view',
    render(root) {
      el = root; const canM = ERP.auth.can('hr.manage');
      root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-id-card"></i> الموارد البشرية</h2><div class="desc">الموظفون، الحضور، السلف، الرواتب وأداء الكاشير</div></div><div class="page-actions"><input type="month" id="hr-month" value="${month}">${canM ? '<button class="btn btn-primary" id="hr-add"><i class="fas fa-user-plus"></i> موظف جديد</button>' : ''}</div></div><div class="kpi-grid mb-4" id="hr-kpis"></div>
        <div class="tabs" id="hr-tabs"><button class="tab active" data-t="emp"><i class="fas fa-users"></i> الموظفون</button><button class="tab" data-t="att"><i class="fas fa-fingerprint"></i> الحضور والانصراف</button><button class="tab" data-t="pay"><i class="fas fa-money-check-dollar"></i> الرواتب</button><button class="tab" data-t="adv"><i class="fas fa-hand-holding-dollar"></i> السلف</button><button class="tab" data-t="perf"><i class="fas fa-ranking-star"></i> أداء الكاشير</button></div>
        <div class="tab-pane active" data-p="emp"><div id="hr-t-emp"></div></div><div class="tab-pane" data-p="att"><div class="flex gap-2 items-center mb-3"><label>التاريخ</label><input type="date" id="hr-att-date" value="${u.todayISO()}" style="max-width:200px"></div><div id="hr-t-att"></div></div><div class="tab-pane" data-p="pay"><div id="hr-t-pay"></div></div><div class="tab-pane" data-p="adv"><div id="hr-t-adv"></div></div><div class="tab-pane" data-p="perf"><div id="hr-t-perf"></div></div>`;
      tables.emp = ERP.ui.table({ el: '#hr-t-emp', rows: [], exportName: 'الموظفون', columns: [{ key: 'name', label: 'الموظف', render: (x, t) => `<div class="flex items-center gap-2"><div class="avatar sm">${e(u.initials(x.name))}</div><div><div class="fw-600">${u.highlight(x.name, t)}</div><div class="text-xs muted">${e(x.code)}</div></div></div>` }, { key: 'job', label: 'الوظيفة', render: x => u.badge(x.job, 'primary') }, { key: 'phone', label: 'الهاتف', render: x => `<span class="num">${e(x.phone || '—')}</span>` }, ...(canM ? [{ key: 'salary', label: 'الراتب', num: true, render: x => u.fmtNum(x.salary), footer: r => u.fmtMoney(u.sum(r.filter(x => x.active !== false), 'salary')) }] : []), { key: 'hireDate', label: 'التعيين', render: x => `<span class="num text-sm">${u.fmtDate(x.hireDate)}</span>` }, { id: 'st', label: 'الحالة', render: x => u.statusBadge(x.active === false ? 'inactive' : 'active'), sortable: false }, { id: 'a', label: '', sortable: false, export: false, class: 'actions', render: x => `<button class="btn btn-icon btn-sm btn-ghost" data-a="view" data-id="${x.id}"><i class="fas fa-eye"></i></button>${canM ? `<button class="btn btn-icon btn-sm btn-ghost" data-a="adv" data-id="${x.id}" data-tip="سلفة"><i class="fas fa-hand-holding-dollar"></i></button><button class="btn btn-icon btn-sm btn-ghost" data-a="edit" data-id="${x.id}"><i class="fas fa-pen"></i></button><button class="btn btn-icon btn-sm btn-ghost text-danger" data-a="del" data-id="${x.id}"><i class="fas fa-trash"></i></button>` : ''}` }], rowClass: x => x.active === false ? 'muted' : '', onRowClick: x => empDetails(x.id) });
      tables.att = ERP.ui.table({ el: '#hr-t-att', rows: [], exportName: 'الحضور', searchable: false, footer: false, columns: [{ key: 'name', label: 'الموظف', render: x => `<div class="fw-600">${e(x.name)}</div><div class="text-xs muted">${e(x.shiftStart)} — ${e(x.shiftEnd)}</div>` }, { id: 'in', label: 'حضور', render: x => x.rec?.in ? `<span class="num">${x.rec.in}</span>` : '—', sortable: false, text: x => x.rec?.in || '' }, { id: 'out', label: 'انصراف', render: x => x.rec?.out ? `<span class="num">${x.rec.out}</span>` : '—', sortable: false, text: x => x.rec?.out || '' }, { id: 'h', label: 'ساعات', num: true, render: x => x.rec?.hours ? u.fmtNum(x.rec.hours, 1) : '—', sortable: false, text: x => x.rec?.hours || '' }, { id: 's', label: 'الحالة', render: x => x.rec ? u.statusBadge(x.rec.status) : u.badge('لم يسجل', 'neutral'), sortable: false, text: x => x.rec?.status || '' }, ...(canM ? [{ id: 'a', label: '', sortable: false, export: false, render: x => `<div class="flex gap-1">${!x.rec?.in ? `<button class="btn btn-sm btn-soft-success" data-att="in" data-id="${x.id}"><i class="fas fa-right-to-bracket"></i> حضور</button>` : ''}${x.rec?.in && !x.rec?.out ? `<button class="btn btn-sm btn-soft-warning" data-att="out" data-id="${x.id}"><i class="fas fa-right-from-bracket"></i> انصراف</button>` : ''}<button class="btn btn-sm btn-ghost" data-att="absent" data-id="${x.id}">غياب</button><button class="btn btn-sm btn-ghost" data-att="leave" data-id="${x.id}">إجازة</button></div>` }] : [])] });
      tables.pay = ERP.ui.table({ el: '#hr-t-pay', rows: [], exportName: 'الرواتب', searchable: false, footer: false, columns: [{ key: 'name', label: 'الموظف', render: x => `<div class="fw-600">${e(x.name)}</div><div class="text-xs muted">${e(x.job)}</div>` }, { key: 'salary', label: 'الأساسي', num: true, render: x => u.fmtNum(x.salary) }, { id: 'abs', label: 'غياب', num: true, render: x => (x.pr ? x.pr.absentDays : x.calc.attendance.absent) + ' يوم', sortable: false }, { id: 'adv', label: 'سلف', num: true, render: x => u.fmtNum(x.pr ? x.pr.advancesDeducted : u.sum(ERP.hr.openAdvances(x.id), 'remaining')), sortable: false }, { id: 'net', label: 'الصافي', num: true, render: x => `<strong>${u.fmtNum(x.pr ? x.pr.net : x.calc.net)}</strong>`, sortable: false, text: x => x.pr ? x.pr.net : x.calc.net }, { id: 'st', label: 'الحالة', render: x => x.pr ? u.badge(`صُرف ${u.fmtDate(x.pr.paidAt)}`, 'success') : u.badge('لم يُصرف', 'warning'), sortable: false }, ...(canM ? [{ id: 'a', label: '', sortable: false, export: false, render: x => x.pr ? `<button class="btn btn-sm btn-ghost" data-slip="${x.pr.id}"><i class="fas fa-print"></i> قسيمة</button>` : `<button class="btn btn-sm btn-success" data-pay="${x.id}"><i class="fas fa-money-check-dollar"></i> صرف</button>` }] : [])] });
      tables.adv = ERP.ui.table({ el: '#hr-t-adv', rows: [], exportName: 'السلف', columns: [{ key: 'date', label: 'التاريخ', render: a => `<span class="num">${u.fmtDate(a.date)}</span>` }, { key: 'employeeName', label: 'الموظف' }, { key: 'amount', label: 'المبلغ', num: true, render: a => u.fmtNum(a.amount), footer: r => u.fmtMoney(u.sum(r, 'amount')) }, { key: 'remaining', label: 'المتبقي', num: true, render: a => `<span class="${a.remaining > 0 ? 'text-warning fw-700' : ''}">${u.fmtNum(a.remaining)}</span>`, footer: r => u.fmtMoney(u.sum(r, 'remaining')) }, { key: 'status', label: 'الحالة', render: a => u.badge(a.status === 'settled' ? 'مسددة' : 'مفتوحة', a.status === 'settled' ? 'success' : 'warning') }, { key: 'notes', label: 'ملاحظات' }] });
      tables.perf = ERP.ui.table({ el: '#hr-t-perf', rows: [], exportName: 'أداء الكاشير', searchable: false, defaultSort: { key: 'total', dir: 'desc' }, columns: [{ key: 'name', label: 'الكاشير', render: (x, t) => `<div class="flex items-center gap-2"><div class="avatar sm">${e(u.initials(x.name))}</div><strong>${e(x.name)}</strong></div>` }, { key: 'invoices', label: 'الفواتير', num: true }, { key: 'total', label: 'المبيعات', num: true, render: x => `<strong>${u.fmtNum(x.total)}</strong>`, footer: r => u.fmtMoney(u.sum(r, 'total')) }, { id: 'avg', label: 'متوسط الفاتورة', num: true, render: x => u.fmtNum(x.total / Math.max(1, x.invoices)), sortValue: x => x.total / Math.max(1, x.invoices) }, { key: 'discounts', label: 'الخصومات', num: true, render: x => u.fmtNum(x.discounts) }, ...(ERP.auth.can('reports.profit') ? [{ key: 'profit', label: 'الربح', num: true, render: x => `<span class="text-success">${u.fmtNum(x.profit)}</span>` }] : [])] });
      $('#hr-tabs', root).onclick = ev => { const t = ev.target.closest('.tab'); if (t) switchTab(t.dataset.t); };
      $('#hr-month', root).onchange = refresh; $('#hr-att-date', root).onchange = refresh;
      root.addEventListener('click', async ev => {
        const b = ev.target.closest('[data-a][data-id]'); if (b) { ev.stopPropagation(); const { a, id } = b.dataset; if (a === 'view') empDetails(id); if (a === 'edit') openForm(id); if (a === 'adv') advance(id); if (a === 'del') { const x = ERP.hr.get(id); if (await ERP.ui.confirm(`حذف الموظف <strong>${e(x.name)}</strong>؟`, { danger: true })) { ERP.hr.remove(id); refresh(); } } return; }
        const at = ev.target.closest('[data-att]'); if (at) { const d = $('#hr-att-date', root).value; const id = at.dataset.id; try { if (at.dataset.att === 'in') { if (d !== u.todayISO()) ERP.hr.markStatus(id, d, 'present'); else ERP.hr.checkIn(id); } else if (at.dataset.att === 'out') ERP.hr.checkOut(id); else ERP.hr.markStatus(id, d, at.dataset.att); refresh(); } catch (err) { ERP.ui.error(err.message); } return; }
        const py = ev.target.closest('[data-pay]'); if (py) return payDialog(py.dataset.pay);
        const sl = ev.target.closest('[data-slip]'); if (sl) return printSlip(ERP.db.collection('payroll').get(sl.dataset.slip));
      });
      if (canM) $('#hr-add', root).onclick = () => openForm();
    },
    onShow(root, params) { if (params.tab) switchTab(params.tab); else refresh(); },
  });
  ERP.bus.on('db:change', u.debounce(ev => { if (el && ERP.router.current() === 'hr' && ['employees', 'attendance', 'advances', 'payroll'].includes(ev?.collection)) refresh(); }, 250));
})();
