/* ==========================================================================
   View: Promotions & discounts
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el;
  function refresh() {
    if (!el) return; const list = ERP.promotions.all(); const today = u.todayISO();
    $('#pr-list', el).innerHTML = list.length ? list.map(p => { const active = ERP.promotions.active().includes(p); const exp = p.to && p.to < today; return `<div class="card card-body flex items-center gap-4 mb-3 ${!p.active ? 'muted' : ''}"><div class="kpi-icon ${active ? 'danger' : 'primary'}" style="width:48px;height:48px"><i class="fas fa-${p.type === 'buy_x_get_y' ? 'gift' : p.type === 'min_total_percent' ? 'receipt' : 'percent'}"></i></div><div class="flex-1"><div class="fw-700">${e(p.name)} ${active ? u.badge('نشط الآن', 'success') : exp ? u.badge('منتهي', 'neutral') : !p.active ? u.badge('معطل', 'neutral') : u.badge('مجدول', 'info')}</div><div class="text-sm muted">${e(ERP.promotions.TYPES[p.type])} — ${p.type === 'percent' ? p.value + '%' : p.type === 'fixed' ? u.fmtMoney(p.value) : p.type === 'buy_x_get_y' ? `اشترِ ${p.buyQty} واحصل على ${p.getQty}` : p.type === 'bundle_price' ? `${p.bundleQty} بـ ${u.fmtMoney(p.value)}` : `${p.value}% للفواتير فوق ${u.fmtMoney(p.minTotal)}`} · ${p.scope === 'all' ? 'كل المنتجات' : p.scope === 'products' ? `${(p.productIds || []).length} منتج` : `${(p.categoryIds || []).length} فئة`}${p.from || p.to ? ` · ${p.from ? u.fmtDate(p.from) : '…'} → ${p.to ? u.fmtDate(p.to) : '…'}` : ''}</div></div><label class="switch"><input type="checkbox" data-t="${p.id}" ${p.active ? 'checked' : ''}><span class="slider"></span></label><button class="btn btn-sm btn-ghost" data-e="${p.id}"><i class="fas fa-pen"></i></button><button class="btn btn-sm btn-ghost text-danger" data-d="${p.id}"><i class="fas fa-trash"></i></button></div>`; }).join('') : '<div class="empty-state"><i class="fas fa-tags"></i><h4>لا عروض بعد</h4><p>أضف عروضاً لتُطبّق تلقائياً في نقطة البيع</p></div>';
  }
  async function form(id = null) {
    const p = id ? ERP.promotions.all().find(x => x.id === id) : { type: 'percent', scope: 'all', active: true, value: 10, productIds: [], categoryIds: [] };
    const cats = ERP.db.collection('categories').all(); const prods = ERP.db.collection('products').all();
    const h = ERP.ui.modal({ title: id ? 'تعديل عرض' : 'عرض جديد', icon: 'tags', size: 'lg', body: `<div class="form-row cols-2"><div class="form-group" style="grid-column:1/-1"><label class="required">اسم العرض</label><input id="pm-name" value="${e(p.name || '')}" placeholder="مثال: خصم نهاية الأسبوع"></div><div class="form-group"><label>نوع العرض</label><select id="pm-type">${Object.entries(ERP.promotions.TYPES).map(([k, v]) => `<option value="${k}" ${p.type === k ? 'selected' : ''}>${v}</option>`).join('')}</select></div><div class="form-group" id="pm-val-g"><label>القيمة</label><input type="number" step="any" id="pm-value" value="${p.value ?? ''}"></div><div class="form-group pm-xy"><label>اشترِ (X)</label><input type="number" id="pm-buy" value="${p.buyQty || 2}"></div><div class="form-group pm-xy"><label>احصل على (Y) مجاناً</label><input type="number" id="pm-get" value="${p.getQty || 1}"></div><div class="form-group pm-bundle"><label>عدد القطع في الحزمة</label><input type="number" id="pm-bqty" value="${p.bundleQty || 3}"></div><div class="form-group pm-min"><label>الحد الأدنى لإجمالي الفاتورة</label><input type="number" step="any" id="pm-min" value="${p.minTotal || 100}"></div><div class="form-group"><label>الحد الأدنى للكمية (اختياري)</label><input type="number" id="pm-minqty" value="${p.minQty || ''}"></div><div class="form-group"><label>يُطبّق على</label><select id="pm-scope"><option value="all" ${p.scope === 'all' ? 'selected' : ''}>كل المنتجات</option><option value="categories" ${p.scope === 'categories' ? 'selected' : ''}>فئات محددة</option><option value="products" ${p.scope === 'products' ? 'selected' : ''}>منتجات محددة</option></select></div><div class="form-group pm-cats" style="grid-column:1/-1"><label>الفئات</label><div class="flex gap-2 flex-wrap">${cats.map(c => `<label class="checkbox"><input type="checkbox" class="pm-cat" value="${c.id}" ${(p.categoryIds || []).includes(c.id) ? 'checked' : ''}> ${e(c.name)}</label>`).join('')}</div></div><div class="form-group pm-prods" style="grid-column:1/-1"><label>المنتجات</label><input id="pm-psearch" placeholder="ابحث لإضافة منتج…"><div class="flex gap-1 flex-wrap mt-2" id="pm-plist"></div></div><div class="form-group"><label>من تاريخ</label><input type="date" id="pm-from" value="${p.from || ''}"></div><div class="form-group"><label>إلى تاريخ</label><input type="date" id="pm-to" value="${p.to || ''}"></div><div class="form-group" style="grid-column:1/-1"><label>أيام الأسبوع (اتركها فارغة لكل الأيام)</label><div class="flex gap-2 flex-wrap">${u.AR_DAYS.map((d, i) => `<label class="checkbox"><input type="checkbox" class="pm-day" value="${i}" ${(p.days || []).includes(i) ? 'checked' : ''}> ${d}</label>`).join('')}</div></div></div>`, footer: `<button class="btn" data-a="c">إلغاء</button><button class="btn btn-primary" data-a="ok"><i class="fas fa-check"></i> حفظ</button>` });
    let pids = [...(p.productIds || [])];
    const renderP = () => { h.$('#pm-plist').innerHTML = pids.map(id => { const x = prods.find(y => y.id === id); return x ? `<span class="badge badge-primary">${e(x.name)} <button data-rm="${id}" style="color:inherit"><i class="fas fa-xmark"></i></button></span>` : ''; }).join('') || '<span class="text-xs muted">لم تُحدد منتجات</span>'; };
    renderP(); h.$('#pm-plist').onclick = ev => { const b = ev.target.closest('[data-rm]'); if (b) { pids = pids.filter(x => x !== b.dataset.rm); renderP(); } };
    ERP.ui.picker(h.$('#pm-psearch'), { source: () => prods, clearOnPick: true, onPick: x => { if (!pids.includes(x.id)) pids.push(x.id); renderP(); } });
    const vis = () => { const t = h.$('#pm-type').value, sc = h.$('#pm-scope').value; h.$$('.pm-xy').forEach(x => x.style.display = t === 'buy_x_get_y' ? '' : 'none'); h.$$('.pm-bundle').forEach(x => x.style.display = t === 'bundle_price' ? '' : 'none'); h.$$('.pm-min').forEach(x => x.style.display = t === 'min_total_percent' ? '' : 'none'); h.$('#pm-val-g').style.display = t === 'buy_x_get_y' ? 'none' : ''; h.$('#pm-val-g label').textContent = t === 'percent' || t === 'min_total_percent' ? 'نسبة الخصم %' : t === 'bundle_price' ? 'سعر الحزمة' : 'قيمة الخصم لكل وحدة'; h.$('.pm-cats').style.display = sc === 'categories' ? '' : 'none'; h.$('.pm-prods').style.display = sc === 'products' ? '' : 'none'; }; vis(); h.$('#pm-type').onchange = vis; h.$('#pm-scope').onchange = vis;
    h.$('[data-a=c]').onclick = () => h.close();
    h.$('[data-a=ok]').onclick = () => { const name = h.$('#pm-name').value.trim(); if (!name) return ERP.ui.warn('اسم العرض مطلوب'); ERP.promotions.save({ ...p, id: p.id, name, type: h.$('#pm-type').value, value: u.num(h.$('#pm-value').value), buyQty: u.num(h.$('#pm-buy').value), getQty: u.num(h.$('#pm-get').value), bundleQty: u.num(h.$('#pm-bqty').value), minTotal: u.num(h.$('#pm-min').value), minQty: u.num(h.$('#pm-minqty').value) || null, scope: h.$('#pm-scope').value, categoryIds: h.$$('.pm-cat:checked').map(c => c.value), productIds: pids, from: h.$('#pm-from').value || null, to: h.$('#pm-to').value || null, days: h.$$('.pm-day:checked').map(c => +c.value) }); h.close(); ERP.ui.success('تم الحفظ'); refresh(); };
  }
  ERP.router.register({
    id: 'promotions', title: 'العروض والخصومات', icon: 'tags', section: 'الإدارة', order: 2, perm: 'promotions.manage',
    render(root) { el = root; root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-tags"></i> العروض والخصومات</h2><div class="desc">عروض تُطبّق تلقائياً في نقطة البيع: نسب، مبالغ، اشترِ X واحصل على Y، حزم، خصم على الإجمالي</div></div><div class="page-actions"><button class="btn btn-primary" id="pr-add"><i class="fas fa-plus"></i> عرض جديد</button></div></div><div id="pr-list"></div>`; $('#pr-add', root).onclick = () => form(); root.addEventListener('click', async ev => { const ed = ev.target.closest('[data-e]'), dl = ev.target.closest('[data-d]'); if (ed) form(ed.dataset.e); if (dl && await ERP.ui.confirm('حذف العرض؟', { danger: true })) { ERP.promotions.remove(dl.dataset.d); refresh(); } }); root.addEventListener('change', ev => { const t = ev.target.closest('[data-t]'); if (t) { const p = ERP.promotions.all().find(x => x.id === t.dataset.t); ERP.promotions.save({ ...p, active: t.checked }); refresh(); } }); },
    onShow() { refresh(); },
  });
})();
