/* ==========================================================================
   View: Purchases — purchase orders, receiving, supplier returns
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el, table;
  const P = () => ERP.db.collection('products');
  function refresh() { if (!table) return; const l = ERP.purchasing.orders(); table.setRows(l); const open = l.filter(p => p.status === 'ordered'); $('#po-kpis', el).innerHTML = [['file-invoice', 'primary', 'أوامر مفتوحة', `${open.length}`], ['sack-dollar', 'info', 'قيمة المفتوح', u.fmtMoney(u.sum(open, 'total'))], ['money-bill-transfer', 'danger', 'غير مسدد', u.fmtMoney(u.sum(l.filter(p => !['cancelled', 'draft'].includes(p.status) && p.type !== 'return'), 'due'))], ['calendar-xmark', 'warning', 'متأخر التوريد', `${open.filter(p => p.expectedDate && p.expectedDate < u.todayISO()).length}`], ['cart-flatbed', 'success', 'مشتريات الشهر', u.fmtMoney(ERP.reports.purchasesSummary(ERP.reports.period('month').from, ERP.reports.period('month').to).total)]].map(k => `<div class="card kpi"><div class="kpi-icon ${k[1]}"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.2rem">${k[3]}</div></div></div>`).join(''); }

  async function openForm(id = null, preset = {}) {
    if (!ERP.auth.require('purchases.manage')) return;
    const po = id ? ERP.purchasing.order(id) : null;
    const sups = ERP.purchasing.suppliers().filter(s => s.active !== false); if (!sups.length) { ERP.ui.warn('أضف مورداً أولاً'); return ERP.views.suppliers.openForm(); }
    const whs = ERP.inventory.warehouses();
    let items = po ? po.items.map(it => ({ ...it })) : (preset.items || []);
    const h = ERP.ui.modal({ title: po ? `تعديل أمر شراء ${e(po.no)}` : 'أمر شراء جديد', icon: 'truck-fast', size: 'xl', body: `
      <div class="form-row"><div class="form-group"><label class="required">المورد</label><select id="po-sup">${u.options(sups, { selected: po?.supplierId || preset.supplierId })}</select></div><div class="form-group"><label>المخزن</label><select id="po-wh">${u.options(whs, { selected: po?.warehouseId || ERP.inventory.defaultWh() })}</select></div><div class="form-group"><label>تاريخ التوريد المتوقع</label><input type="date" id="po-exp" value="${po?.expectedDate || ''}"></div><div class="form-group"><label>رقم فاتورة المورد</label><input id="po-ref" value="${e(po?.refNo || '')}"></div></div>
      <div class="form-group"><label>إضافة صنف</label><div class="flex gap-2"><input id="po-p" placeholder="ابحث بالاسم أو امسح الباركود…" autocomplete="off" class="flex-1"><button class="btn btn-outline" id="po-new-p"><i class="fas fa-plus"></i> منتج جديد</button><button class="btn btn-outline" id="po-low" data-tip="إضافة كل النواقص لهذا المورد"><i class="fas fa-wand-magic-sparkles"></i> النواقص</button></div></div>
      <div class="doc-lines" id="po-lines"></div>
      <div class="form-row mt-3"><div class="form-group"><label>خصم على الفاتورة</label><input type="number" step="any" min="0" id="po-disc" value="${po?.discount || 0}"></div><div class="form-group"><label>ضريبة %</label><input type="number" step="any" min="0" id="po-tax" value="${po?.taxRate ?? (ERP.settings.get('taxEnabled') ? ERP.settings.get('taxRate') : 0)}"></div><div class="form-group" style="grid-column:span 2"><label>ملاحظات</label><input id="po-notes" value="${e(po?.notes || '')}"></div></div>
      <div class="doc-summary"><div class="doc-summary-box" id="po-sum"></div></div>`, footer: `<button class="btn" data-a="c">إلغاء</button><div class="flex-1"></div><button class="btn btn-outline" data-a="draft"><i class="fas fa-file"></i> حفظ كمسودة</button><button class="btn btn-primary" data-a="ok"><i class="fas fa-check"></i> ${po ? 'حفظ التعديلات' : 'اعتماد الأمر'}</button>${!po ? '<button class="btn btn-success" data-a="recv"><i class="fas fa-box-open"></i> اعتماد واستلام فوري</button>' : ''}` });
    const calc = () => { const c = items.map(it => u.num(it.qty) * u.num(it.cost)); const sub = u.sum(c); const d = u.num(h.$('#po-disc').value); const tax = u.round((sub - d) * u.num(h.$('#po-tax').value) / 100); h.$('#po-sum').innerHTML = `<div class="tot-row"><span>الإجمالي</span><span class="val">${u.fmtNum(sub)}</span></div><div class="tot-row"><span>الخصم</span><span class="val">-${u.fmtNum(d)}</span></div><div class="tot-row"><span>الضريبة</span><span class="val">${u.fmtNum(tax)}</span></div><div class="tot-row grand"><span>الصافي</span><span class="val">${u.fmtMoney(sub - d + tax)}</span></div>`; };
    const G = '2fr 110px 90px 110px 110px 110px 120px 40px';
    const unitSel = (it, i, p) => { const list = ERP.units.list(p); const uid = ERP.units.lineUnit(it); return list.length ? `<select data-i="${i}" data-k="unitId" title="وحدة الشراء"><option value="">${e(ERP.units.baseName(p))}</option>${list.map(x => `<option value="${e(x.id)}" ${x.id === uid ? 'selected' : ''}>${e(x.name)} ×${u.fmtQty(x.factor)}</option>`).join('')}</select>` : `<span class="text-xs muted">${e(ERP.units.baseName(p))}</span>`; };
    const render = () => { h.$('#po-lines').innerHTML = `<div class="doc-line head" style="grid-template-columns:${G}"><span>الصنف</span><span>الوحدة</span><span>الكمية</span><span>سعر الشراء</span><span>سعر البيع الجديد</span><span>الصلاحية</span><span>الإجمالي</span><span></span></div>` + (items.map((it, i) => { const p = P().get(it.productId); const margin = it.newPrice && it.cost ? ((it.newPrice - it.cost) / it.newPrice * 100).toFixed(0) : null; const uf = u.num(it.factor, 1) || 1, uid = ERP.units.lineUnit(it); return `<div class="doc-line" style="grid-template-columns:${G}"><div><div class="fw-600 text-sm">${e(p ? p.name : it.name)}</div><div class="text-xs muted">مخزون ${u.fmtQty(p?.stock || 0)} · تكلفة حالية ${u.fmtNum((p?.cost || 0) * uf)} · بيع ${u.fmtNum(p ? ERP.units.price(p, uid) : 0)}${uf > 1 ? ` · = ${u.fmtQty(u.num(it.qty) * uf)} ${e(ERP.units.baseName(p))}` : ''}</div></div>${p ? unitSel(it, i, p) : '<span></span>'}<input type="number" step="any" min="0" value="${it.qty}" data-i="${i}" data-k="qty" class="num"><input type="number" step="any" min="0" value="${it.cost}" data-i="${i}" data-k="cost" class="num"><input type="number" step="any" min="0" value="${it.newPrice || ''}" placeholder="${p ? ERP.units.price(p, uid) : ''}" data-i="${i}" data-k="newPrice" class="num" title="${margin !== null ? 'هامش ' + margin + '%' : ''}"><input type="date" value="${it.expiry || ''}" data-i="${i}" data-k="expiry" ${p?.trackExpiry ? '' : 'style="opacity:.4"'}><span class="num fw-700">${u.fmtNum(u.num(it.qty) * u.num(it.cost))}</span><button class="btn btn-icon btn-sm btn-ghost text-danger" data-d="${i}"><i class="fas fa-xmark"></i></button></div>`; }).join('') || '<div class="p-4 text-center muted">لا أصناف — ابحث وأضف أصنافاً</div>'); calc(); };
    render();
    const addProduct = (p, unit = null) => { const uid = unit ? unit.id : null, f = unit ? u.num(unit.factor, 1) : 1; const ex = items.find(it => it.productId === p.id && ERP.units.lineUnit(it) === uid); if (ex) ex.qty = u.num(ex.qty) + 1; else items.push({ productId: p.id, name: p.name, qty: unit ? 1 : Math.max(1, u.num(p.reorderQty)), cost: unit ? (u.num(unit.cost) || u.round(u.num(p.cost) * f, 4)) : p.cost, newPrice: null, expiry: '', unitId: uid, unitName: unit ? ERP.units.name(p, uid) : '', factor: f }); render(); };
    ERP.ui.picker(h.$('#po-p'), { source: () => P().all().filter(p => p.active !== false), sub: p => `${p.code} · مخزون ${u.fmtQty(p.stock)} · تكلفة ${u.fmtNum(p.cost)}`, clearOnPick: true, onPick: addProduct });
    h.$('#po-p').addEventListener('keydown', ev => { if (ev.key === 'Enter') { const r = ERP.inventory.resolveScan(ev.target.value.trim()); if (r) { addProduct(r.product, r.unit || null); ev.target.value = ''; } } });
    h.$('#po-new-p').onclick = async () => { await ERP.views.products.openForm(null, {}); };
    h.$('#po-low').onclick = () => { const sid = h.$('#po-sup').value; const list = ERP.inventory.reorderSuggestions().filter(s => !s.supplierId || s.supplierId === sid); if (!list.length) return ERP.ui.info('لا نواقص لهذا المورد'); list.forEach(s => { if (!items.find(it => it.productId === s.product.id)) items.push({ productId: s.product.id, name: s.product.name, qty: Math.ceil(s.suggested), cost: s.product.cost, newPrice: null, expiry: '' }); }); render(); };
    h.$('#po-lines').addEventListener('change', ev => { if (ev.target.dataset.k !== 'unitId') return; const i = +ev.target.dataset.i, it = items[i], p = P().get(it.productId); const nu = ev.target.value || null, un = nu ? ERP.units.get(p, nu) : null; const f0 = u.num(it.factor, 1) || 1, f1 = un ? u.num(un.factor, 1) : 1; Object.assign(it, { unitId: nu, unitName: un ? ERP.units.name(p, nu) : '', factor: f1, cost: un && u.num(un.cost) ? u.num(un.cost) : u.round(u.num(it.cost) / f0 * f1, 4), newPrice: null }); render(); }); // switching carton ⇄ piece rescales the cost
    h.$('#po-lines').addEventListener('input', ev => { const i = +ev.target.dataset.i, k = ev.target.dataset.k; if (k === undefined || k === 'unitId') return; items[i][k] = k === 'expiry' ? ev.target.value : (ev.target.value === '' ? null : u.num(ev.target.value)); if (k === 'qty' || k === 'cost') { const row = ev.target.closest('.doc-line'); row.querySelector('span.num').textContent = u.fmtNum(u.num(items[i].qty) * u.num(items[i].cost)); calc(); } });
    h.$('#po-lines').addEventListener('click', ev => { const d = ev.target.closest('[data-d]'); if (d) { items.splice(+d.dataset.d, 1); render(); } });
    h.$('#po-disc').oninput = h.$('#po-tax').oninput = calc;
    h.$('[data-a=c]').onclick = () => h.close();
    const save = (status, receive = false) => { items = items.filter(it => u.num(it.qty) > 0); if (!items.length) return ERP.ui.warn('أضف أصنافاً'); const data = { supplierId: h.$('#po-sup').value, items, discount: u.num(h.$('#po-disc').value), taxRate: u.num(h.$('#po-tax').value), warehouseId: h.$('#po-wh').value, expectedDate: h.$('#po-exp').value, notes: h.$('#po-notes').value, refNo: h.$('#po-ref').value }; try { let doc; if (po) { doc = ERP.purchasing.update(id, data); if (status === 'ordered' && po.status === 'draft') ERP.db.collection('purchases').update(id, { status: 'ordered' }); } else { doc = ERP.purchasing.create({ ...data, status }); if (receive) doc = ERP.purchasing.receive(doc.id); } h.close(); ERP.ui.success(`تم ${receive ? 'الاستلام' : 'الحفظ'} — ${doc.no}`); if (receive) details(doc.id); } catch (err) { ERP.ui.error(err.message); } };
    h.$('[data-a=draft]').onclick = () => save('draft'); h.$('[data-a=ok]').onclick = () => save('ordered'); const rv = h.$('[data-a=recv]'); if (rv) rv.onclick = () => save('ordered', true);
  }
  async function receiveDialog(id) {
    if (!ERP.auth.require('purchases.manage')) return;
    const po = ERP.purchasing.order(id);
    const pend = po.items.filter(it => (it.received || 0) < it.qty);
    const h = ERP.ui.modal({ title: `استلام ${e(po.no)}`, icon: 'box-open', size: 'lg', body: `<div class="alert alert-info mb-3"><i class="fas fa-circle-info"></i> يمكنك استلام كامل الكميات أو جزء منها. سيتم تحديث المخزون والتكلفة المتوسطة تلقائياً.</div><div class="doc-lines">${`<div class="doc-line head" style="grid-template-columns:2fr 90px 110px 110px 120px 110px"><span>الصنف</span><span>المطلوب</span><span>مستلم سابقاً</span><span>استلام الآن</span><span>التكلفة الفعلية</span><span>الصلاحية</span></div>` + pend.map((it, i) => { const p = P().get(it.productId); return `<div class="doc-line" style="grid-template-columns:2fr 90px 110px 110px 120px 110px"><span class="text-sm fw-600">${e(it.name)}</span><span class="num">${u.fmtQty(it.qty)}</span><span class="num">${u.fmtQty(it.received || 0)}</span><input type="number" step="any" min="0" max="${it.qty - (it.received || 0)}" value="${it.qty - (it.received || 0)}" data-i="${i}" data-k="qty" class="num"><input type="number" step="any" min="0" value="${it.cost}" data-i="${i}" data-k="cost" class="num"><input type="date" value="${it.expiry || ''}" data-i="${i}" data-k="expiry" ${p?.trackExpiry ? '' : 'style="opacity:.4"'}></div>`; }).join('')}</div><div class="text-xs muted mt-3"><i class="fas fa-circle-info"></i> تكلفة المنتجات تتحدث تلقائياً بالمتوسط المرجح (بعد خصم المورد) عشان الحسابات تفضل مطابقة للمخزون</div><label class="checkbox mt-2"><input type="checkbox" id="rc-price" checked> تطبيق أسعار البيع الجديدة المحددة في الأمر</label>`, footer: `<button class="btn" data-a="c">إلغاء</button><button class="btn btn-success" data-a="ok"><i class="fas fa-check"></i> تأكيد الاستلام</button>` });
    const rec = pend.map(it => ({ productId: it.productId, unitId: ERP.units.lineUnit(it), qty: it.qty - (it.received || 0), cost: it.cost, expiry: it.expiry || '', newPrice: it.newPrice }));
    h.body.addEventListener('input', ev => { const i = +ev.target.dataset.i, k = ev.target.dataset.k; if (k) rec[i][k] = k === 'expiry' ? ev.target.value : u.num(ev.target.value); });
    h.$('[data-a=c]').onclick = () => h.close();
    h.$('[data-a=ok]').onclick = () => { try { const r = ERP.purchasing.receive(id, rec.filter(x => x.qty > 0), { updatePrices: h.$('#rc-price').checked }); h.close(); ERP.ui.success(r.status === 'received' ? 'تم الاستلام الكامل' : 'تم الاستلام الجزئي'); } catch (err) { ERP.ui.error(err.message); } };
  }
  function details(id) {
    const po = ERP.purchasing.order(id); if (!po) return; const isRet = po.type === 'return';
    const canM = ERP.auth.can('purchases.manage'), canP = ERP.auth.can('purchases.pay');
    const h = ERP.ui.view(`${isRet ? 'مرتجع شراء' : 'أمر شراء'} <span class="num">${e(po.no)}</span> ${u.statusBadge(po.status)}`, `
      <div class="detail-grid mb-3"><div class="detail-item"><div class="dl">المورد</div><div class="dv"><a href="#/suppliers?id=${po.supplierId}">${e(po.supplierName)}</a></div></div><div class="detail-item"><div class="dl">التاريخ</div><div class="dv num">${u.fmtDateTime(po.date)}</div></div><div class="detail-item"><div class="dl">المخزن</div><div class="dv">${e((ERP.db.collection('warehouses').get(po.warehouseId) || {}).name || '—')}</div></div>${po.expectedDate ? `<div class="detail-item"><div class="dl">موعد التوريد</div><div class="dv num ${po.status === 'ordered' && po.expectedDate < u.todayISO() ? 'text-danger' : ''}">${u.fmtDate(po.expectedDate)}</div></div>` : ''}${po.receivedAt ? `<div class="detail-item"><div class="dl">تاريخ الاستلام</div><div class="dv num">${u.fmtDateTime(po.receivedAt)}</div></div>` : ''}${po.refNo ? `<div class="detail-item"><div class="dl">فاتورة المورد</div><div class="dv num">${e(po.refNo)}</div></div>` : ''}</div>
      <div class="table-wrap"><table class="table table-compact"><thead><tr><th>الصنف</th><th class="num">الكمية</th>${!isRet ? '<th class="num">المستلم</th>' : ''}<th class="num">التكلفة</th>${!isRet ? '<th class="num">سعر بيع جديد</th>' : ''}<th class="num">الإجمالي</th></tr></thead><tbody>${po.items.map(it => `<tr><td>${e(it.name)}${it.expiry ? `<div class="text-xs muted">صلاحية ${u.fmtDate(it.expiry)}</div>` : ''}</td><td class="num">${u.fmtQty(it.qty)}</td>${!isRet ? `<td class="num ${(it.received || 0) >= it.qty ? 'text-success' : (it.received || 0) > 0 ? 'text-warning' : ''}">${u.fmtQty(it.received || 0)}</td>` : ''}<td class="num">${u.fmtNum(it.cost)}</td>${!isRet ? `<td class="num">${it.newPrice ? u.fmtNum(it.newPrice) : '—'}</td>` : ''}<td class="num fw-700">${u.fmtNum(it.total)}</td></tr>`).join('')}</tbody></table></div>
      <div class="doc-summary"><div class="doc-summary-box"><div class="tot-row"><span>الإجمالي</span><span class="val">${u.fmtNum(po.subtotal)}</span></div>${po.discount ? `<div class="tot-row"><span>الخصم</span><span class="val text-danger">-${u.fmtNum(po.discount)}</span></div>` : ''}${po.tax ? `<div class="tot-row"><span>الضريبة</span><span class="val">${u.fmtNum(po.tax)}</span></div>` : ''}<div class="tot-row grand"><span>الصافي</span><span class="val">${u.fmtMoney(po.total)}</span></div>${!isRet ? `<div class="tot-row"><span>المدفوع</span><span class="val">${u.fmtNum(po.paid)}</span></div><div class="tot-row"><span class="${po.due > 0 ? 'text-danger fw-700' : ''}">المتبقي</span><span class="val ${po.due > 0 ? 'text-danger' : ''}">${u.fmtNum(po.due)}</span></div>` : ''}</div></div>
      ${po.notes ? `<div class="alert alert-info mt-3"><i class="fas fa-note-sticky"></i> ${e(po.notes)}</div>` : ''}`,
      { size: 'lg', footer: `<button class="btn" data-a="close">إغلاق</button><div class="flex-1"></div>${canM && ['draft', 'ordered'].includes(po.status) ? `<button class="btn btn-soft-danger" data-a="cancel"><i class="fas fa-ban"></i> إلغاء الأمر</button><button class="btn btn-outline" data-a="edit"><i class="fas fa-pen"></i> تعديل</button>` : ''}${canM && po.status === 'ordered' ? `<button class="btn btn-success" data-a="recv"><i class="fas fa-box-open"></i> استلام</button>` : ''}${canM && !isRet && po.items.some(i => i.received > 0) ? `<button class="btn btn-soft-warning" data-a="ret"><i class="fas fa-rotate-left"></i> مرتجع للمورد</button>` : ''}${canP && po.due > 0 ? `<button class="btn btn-soft-success" data-a="pay"><i class="fas fa-money-bill-transfer"></i> سداد</button>` : ''}<button class="btn btn-primary" data-a="print"><i class="fas fa-print"></i> طباعة</button>` });
    h.$('[data-a=close]').onclick = () => h.close(); h.$('[data-a=print]').onclick = () => ERP.print.purchase(po);
    const q = a => h.$(`[data-a=${a}]`);
    if (q('edit')) q('edit').onclick = () => { h.close(); openForm(id); };
    if (q('recv')) q('recv').onclick = () => { h.close(); receiveDialog(id); };
    if (q('pay')) q('pay').onclick = () => { h.close(); ERP.views.suppliers.payDialog(po.supplierId, id); };
    if (q('cancel')) q('cancel').onclick = async () => { if (await ERP.ui.confirm('إلغاء أمر الشراء؟', { danger: true })) { try { ERP.purchasing.cancel(id); h.close(); ERP.ui.success('تم الإلغاء'); } catch (err) { ERP.ui.error(err.message); } } };
    if (q('ret')) q('ret').onclick = () => { h.close(); returnDialog(po); };
  }
  async function returnDialog(po) {
    const items = po.items.filter(it => it.received > 0).map(it => ({ productId: it.productId, name: it.name, max: it.received, qty: 0, cost: it.cost, unitId: ERP.units.lineUnit(it), unitName: it.unitName || '', factor: u.num(it.factor, 1) || 1 }));
    const h = ERP.ui.modal({ title: `مرتجع للمورد — ${e(po.supplierName)}`, icon: 'rotate-left', size: 'lg', body: `<div class="doc-lines"><div class="doc-line head" style="grid-template-columns:2fr 100px 120px 120px"><span>الصنف</span><span>المستلم</span><span>كمية الإرجاع</span><span>التكلفة</span></div>${items.map((it, i) => `<div class="doc-line" style="grid-template-columns:2fr 100px 120px 120px"><span>${e(it.name)}</span><span class="num">${u.fmtQty(it.max)}</span><input type="number" step="any" min="0" max="${it.max}" value="0" data-i="${i}" data-k="qty" class="num"><input type="number" step="any" value="${it.cost}" data-i="${i}" data-k="cost" class="num"></div>`).join('')}</div><div class="form-group mt-3"><label>السبب</label><input id="pr-note" placeholder="بضاعة معيبة / خطأ في التوريد…"></div>`, footer: `<button class="btn" data-a="c">إلغاء</button><button class="btn btn-warning" data-a="ok">تنفيذ المرتجع</button>` });
    h.body.addEventListener('input', ev => { const i = +ev.target.dataset.i, k = ev.target.dataset.k; if (k) items[i][k] = u.num(ev.target.value); });
    h.$('[data-a=c]').onclick = () => h.close();
    h.$('[data-a=ok]').onclick = () => { const lines = items.filter(it => it.qty > 0).map(it => ({ productId: it.productId, name: it.name, qty: Math.min(it.qty, it.max), cost: it.cost, unitId: it.unitId, unitName: it.unitName, factor: it.factor })); if (!lines.length) return ERP.ui.warn('حدد كميات'); try { const r = ERP.purchasing.returnToSupplier({ supplierId: po.supplierId, items: lines, notes: h.$('#pr-note').value, poId: po.id }); h.close(); ERP.ui.success(`تم المرتجع ${r.no}`); } catch (err) { ERP.ui.error(err.message); } };
  }
  ERP.views.purchases = { openForm, details, receiveDialog };
  ERP.router.register({
    id: 'purchases', title: 'المشتريات', icon: 'cart-flatbed', section: 'العمليات', order: 5, perm: 'purchases.view',
    badge() { const n = ERP.purchasing.orders().filter(p => p.status === 'ordered' && p.expectedDate && p.expectedDate < u.todayISO()).length; return n ? { text: n, kind: 'danger' } : null; },
    render(root) {
      el = root; const canM = ERP.auth.can('purchases.manage');
      root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-cart-flatbed"></i> المشتريات</h2><div class="desc">أوامر الشراء، الاستلام، فواتير الموردين والمرتجعات</div></div><div class="page-actions">${canM ? `<button class="btn btn-outline" id="po-auto"><i class="fas fa-wand-magic-sparkles"></i> اقتراحات إعادة الطلب</button><button class="btn btn-primary" id="po-add"><i class="fas fa-plus"></i> أمر شراء</button>` : ''}</div></div><div class="kpi-grid mb-4" id="po-kpis"></div><div id="po-table"></div>`;
      table = ERP.ui.table({ el: '#po-table', rows: [], exportName: 'المشتريات', defaultSort: { key: 'date', dir: 'desc' }, toolbarExtra: `<select id="po-f" style="min-width:150px"><option value="">كل الحالات</option><option value="draft">مسودة</option><option value="ordered">مطلوب</option><option value="received">مستلم</option><option value="cancelled">ملغي</option><option value="return">مرتجعات</option><option value="due">غير مسدد</option></select>`, columns: [
        { key: 'no', label: 'الرقم', render: (p, t) => `<strong class="num">${u.highlight(p.no, t)}</strong>${p.type === 'return' ? ' ' + u.badge('مرتجع', 'purple') : ''}${p.partial ? ' ' + u.badge('جزئي', 'warning') : ''}`, text: p => p.no },
        { key: 'date', label: 'التاريخ', render: p => `<span class="num text-sm">${u.fmtDate(p.date)}</span>`, text: p => u.fmtDate(p.date) },
        { key: 'supplierName', label: 'المورد', render: (p, t) => u.highlight(p.supplierName, t) },
        { id: 'n', label: 'الأصناف', num: true, render: p => p.items.length, sortValue: p => p.items.length, text: p => p.items.length },
        { key: 'total', label: 'الصافي', num: true, render: p => `<strong>${u.fmtNum(p.total)}</strong>`, footer: r => u.fmtMoney(u.sum(r.filter(p => p.type !== 'return' && p.status !== 'cancelled'), 'total')) },
        { key: 'due', label: 'المتبقي', num: true, render: p => p.due > 0 ? `<span class="text-danger fw-700">${u.fmtNum(p.due)}</span>` : '—', footer: r => `<span class="text-danger">${u.fmtMoney(u.sum(r.filter(p => p.status !== 'cancelled'), 'due'))}</span>` },
        { key: 'expectedDate', label: 'التوريد', render: p => p.expectedDate ? `<span class="num text-sm ${p.status === 'ordered' && p.expectedDate < u.todayISO() ? 'text-danger fw-700' : ''}">${u.fmtDate(p.expectedDate)}</span>` : '—' },
        { key: 'status', label: 'الحالة', render: p => u.statusBadge(p.status), text: p => p.status },
        { id: 'a', label: '', sortable: false, export: false, class: 'actions', render: p => `<button class="btn btn-icon btn-sm btn-ghost" data-a="view" data-id="${p.id}"><i class="fas fa-eye"></i></button>${canM && p.status === 'ordered' ? `<button class="btn btn-icon btn-sm btn-soft-success" data-a="recv" data-id="${p.id}" data-tip="استلام"><i class="fas fa-box-open"></i></button>` : ''}${canM && ['draft', 'cancelled'].includes(p.status) ? `<button class="btn btn-icon btn-sm btn-ghost text-danger" data-a="del" data-id="${p.id}"><i class="fas fa-trash"></i></button>` : ''}` },
      ], rowClass: p => p.status === 'cancelled' ? 'muted' : '', onRowClick: p => details(p.id) });
      $('#po-f', root).onchange = ev => { const v = ev.target.value; table.setRows(ERP.purchasing.orders().filter(p => !v || (v === 'return' ? p.type === 'return' : v === 'due' ? p.due > 0 && p.status !== 'cancelled' : p.status === v && p.type !== 'return'))); };
      root.addEventListener('click', async ev => { const b = ev.target.closest('[data-a][data-id]'); if (!b) return; ev.stopPropagation(); const { a, id } = b.dataset; if (a === 'view') details(id); if (a === 'recv') receiveDialog(id); if (a === 'del') { if (await ERP.ui.confirm('حذف الأمر؟', { danger: true })) { try { ERP.purchasing.remove(id); } catch (err) { ERP.ui.error(err.message); } } } });
      if (canM) { $('#po-add', root).onclick = () => openForm(); $('#po-auto', root).onclick = () => { const s = ERP.inventory.reorderSuggestions(); if (!s.length) return ERP.ui.info('لا توجد نواقص حالياً 🎉'); const h = ERP.ui.view('اقتراحات إعادة الطلب', `<div class="table-wrap"><table class="table table-compact"><thead><tr><th>الصنف</th><th class="num">الرصيد</th><th class="num">الحد الأدنى</th><th class="num">مبيعات/يوم</th><th class="num">تغطية</th><th class="num">مقترح</th><th>المورد</th></tr></thead><tbody>${s.map(x => `<tr><td>${e(x.product.name)}</td><td class="num text-danger">${u.fmtQty(x.product.stock)}</td><td class="num">${u.fmtQty(x.product.minStock ?? 5)}</td><td class="num">${u.fmtNum(x.perDay, 2)}</td><td class="num">${x.daysOfCover === null ? '<span class="muted">—</span>' : x.daysOfCover + ' يوم'}</td><td class="num fw-700">${u.fmtQty(x.suggested)}</td><td>${e((ERP.purchasing.supplier(x.supplierId) || {}).name || '<span class="muted">غير محدد</span>')}</td></tr>`).join('')}</tbody></table></div>`, { footer: `<button class="btn" data-a="close">إغلاق</button><button class="btn btn-primary" data-a="gen"><i class="fas fa-wand-magic-sparkles"></i> إنشاء مسودات أوامر شراء حسب المورد</button>` }); h.$('[data-a=close]').onclick = () => h.close(); h.$('[data-a=gen]').onclick = () => { const c = ERP.purchasing.autoReorderDrafts(); h.close(); ERP.ui.success(c.length ? `تم إنشاء ${c.length} مسودة` : 'لا أصناف لها مورد محدد — حدد الموردين في بيانات المنتجات'); }; }; }
    },
    onShow(root, params) { refresh(); if (params.id) details(params.id); },
  });
  ERP.bus.on('db:change', u.debounce(ev => { if (table && ERP.router.current() === 'purchases' && ['purchases', 'payments'].includes(ev?.collection)) refresh(); }, 250));
})();
