/* ==========================================================================
   View: Reports & Analytics
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el, tab = 'sales', from = ERP.utils.toISODate(ERP.utils.startOfMonth()), to = ERP.utils.todayISO();
  const canProfit = () => ERP.auth.can('reports.profit');
  function kp(list) { return `<div class="kpi-grid mb-4">${list.map(k => `<div class="card kpi"><div class="kpi-icon ${k[1]}"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.2rem">${k[3]}</div>${k[4] ? `<div class="text-xs muted">${k[4]}</div>` : ''}</div></div>`).join('')}</div>`; }
  function tbl(cols, rows, foot) { return `<div class="table-wrap"><table class="table table-compact"><thead><tr>${cols.map(c => `<th class="${c.num ? 'num' : ''}">${c.label}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr>${r.map((v, i) => `<td class="${cols[i].num ? 'num' : ''}">${v}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${cols.length}" class="text-center muted p-4">لا بيانات في هذه الفترة</td></tr>`}</tbody>${foot ? `<tfoot><tr>${foot.map((v, i) => `<td class="${cols[i].num ? 'num' : ''}">${v}</td>`).join('')}</tr></tfoot>` : ''}</table></div>`; }
  let lastPrint = null;

  function refresh() {
    if (!el) return; from = $('#rp-from', el).value; to = $('#rp-to', el).value; const box = $('#rp-body', el); const cp = canProfit();
    if (tab === 'sales') {
      const s = ERP.reports.salesSummary(from, to); const days = ERP.reports.salesByDay(from, to); const hours = ERP.reports.salesByHour(from, to); const wd = ERP.reports.salesByWeekday(from, to); const mix = ERP.reports.paymentMix(from, to);
      box.innerHTML = kp([['sack-dollar', 'primary', 'صافي المبيعات', u.fmtMoney(s.net), `${s.count} فاتورة`], ['rotate-left', 'warning', 'المرتجعات', u.fmtMoney(s.returns), `${s.returnsCount} عملية`], ...(cp ? [['chart-line', 'success', 'مجمل الربح', u.fmtMoney(s.grossProfit), `هامش ${s.margin.toFixed(1)}%`]] : []), ['receipt', 'info', 'متوسط الفاتورة', u.fmtMoney(s.avg), `${u.fmtQty(s.items)} قطعة`], ['percent', 'danger', 'الخصومات', u.fmtMoney(s.discounts)], ['hand-holding-dollar', 'purple', 'مبيعات آجلة', u.fmtMoney(s.credit), `${s.customers} عميل`]]) + `<div class="dash-grid"><div class="card"><div class="card-header"><h3><i class="fas fa-chart-area"></i> المبيعات اليومية</h3></div><div class="card-body"><div class="chart-box"><canvas id="rp-c1"></canvas></div></div></div><div class="card"><div class="card-header"><h3><i class="fas fa-wallet"></i> طرق الدفع</h3></div><div class="card-body"><div class="chart-box"><canvas id="rp-c2"></canvas></div></div></div></div><div class="dash-grid"><div class="card"><div class="card-header"><h3><i class="fas fa-clock"></i> ساعات الذروة</h3></div><div class="card-body"><div class="chart-box sm"><canvas id="rp-c3"></canvas></div></div></div><div class="card"><div class="card-header"><h3><i class="fas fa-calendar-week"></i> أيام الأسبوع</h3></div><div class="card-body"><div class="chart-box sm"><canvas id="rp-c4"></canvas></div></div></div></div><div class="card mt-4"><div class="card-header"><h3><i class="fas fa-table"></i> تفصيل يومي</h3></div>${tbl([{ label: 'اليوم' }, { label: 'التاريخ' }, { label: 'الفواتير', num: true }, { label: 'المبيعات', num: true }, { label: 'المرتجعات', num: true }, ...(cp ? [{ label: 'الربح', num: true }] : [])], days.filter(d => d.count || d.returns).map(d => [u.dayName(d.date), u.fmtDate(d.date), d.count, u.fmtNum(d.total), d.returns ? u.fmtNum(d.returns) : '—', ...(cp ? [u.fmtNum(d.profit)] : [])]), ['', 'الإجمالي', s.count, u.fmtNum(s.gross), u.fmtNum(s.returns), ...(cp ? [u.fmtNum(s.grossProfit)] : [])])}</div>`;
      ERP.charts.line('#rp-c1', { labels: days.map(d => u.fmtDate(d.date).slice(0, 5)), series: [{ label: 'المبيعات', data: days.map(d => u.round(d.total)) }, ...(cp ? [{ label: 'الربح', data: days.map(d => u.round(d.profit)), color: '#16a34a' }] : [])] });
      ERP.charts.doughnut('#rp-c2', { labels: mix.map(m => m.name), data: mix.map(m => u.round(m.total)) });
      ERP.charts.bar('#rp-c3', { labels: hours.map(h => `${h.hour}`), series: [{ label: 'المبيعات', data: hours.map(h => u.round(h.total)) }] });
      ERP.charts.bar('#rp-c4', { labels: wd.map(w => w.day), series: [{ label: 'المبيعات', data: wd.map(w => u.round(w.total)), color: '#7c3aed' }] });
      lastPrint = () => ERP.print.table({ title: 'تقرير المبيعات', subtitle: `${u.fmtDate(from)} — ${u.fmtDate(to)}`, columns: [{ label: 'التاريخ' }, { label: 'الفواتير', num: true }, { label: 'المبيعات', num: true }, { label: 'المرتجعات', num: true }, ...(cp ? [{ label: 'الربح', num: true }] : [])], rows: days.filter(d => d.count).map(d => [u.fmtDate(d.date), d.count, u.fmtNum(d.total), u.fmtNum(d.returns), ...(cp ? [u.fmtNum(d.profit)] : [])]), summary: [{ label: 'صافي المبيعات', value: u.fmtMoney(s.net) }, { label: 'الفواتير', value: s.count }, ...(cp ? [{ label: 'مجمل الربح', value: u.fmtMoney(s.grossProfit) }] : [])] });
    } else if (tab === 'products') {
      const top = ERP.reports.topProducts(from, to, 50); const cats = ERP.reports.salesByCategory(from, to); const byQty = ERP.reports.topProducts(from, to, 10, 'qty');
      box.innerHTML = `<div class="dash-grid"><div class="card"><div class="card-header"><h3><i class="fas fa-fire"></i> الأكثر مبيعاً (كمية)</h3></div><div class="card-body"><div class="chart-box"><canvas id="rp-c1"></canvas></div></div></div><div class="card"><div class="card-header"><h3><i class="fas fa-chart-pie"></i> حسب الفئة</h3></div><div class="card-body"><div class="chart-box"><canvas id="rp-c2"></canvas></div></div></div></div><div class="card mt-4"><div class="card-header"><h3><i class="fas fa-ranking-star"></i> أداء المنتجات</h3></div>${tbl([{ label: '#' }, { label: 'المنتج' }, { label: 'الكمية', num: true }, { label: 'المبيعات', num: true }, ...(cp ? [{ label: 'التكلفة', num: true }, { label: 'الربح', num: true }, { label: 'الهامش', num: true }] : []), { label: 'نسبة من المبيعات', num: true }], top.map((p, i) => [i + 1, e(p.name), u.fmtQty(p.qty), u.fmtNum(p.total), ...(cp ? [u.fmtNum(p.cost), `<span class="${p.profit < 0 ? 'text-danger' : 'text-success'}">${u.fmtNum(p.profit)}</span>`, p.margin.toFixed(1) + '%'] : []), `<div class="flex items-center gap-2"><div class="progress flex-1" style="width:80px"><div class="progress-bar" style="width:${u.pct(p.total, u.sum(top, 'total'))}%"></div></div>${u.pct(p.total, u.sum(top, 'total')).toFixed(1)}%</div>`]))}</div>`;
      ERP.charts.bar('#rp-c1', { labels: byQty.map(p => p.name.slice(0, 18)), series: [{ label: 'الكمية', data: byQty.map(p => u.round(p.qty)) }], horizontal: true });
      ERP.charts.doughnut('#rp-c2', { labels: cats.map(c => c.name), data: cats.map(c => u.round(c.total)), colors: cats.map(c => c.color) });
      lastPrint = () => ERP.print.table({ title: 'تقرير أداء المنتجات', subtitle: `${u.fmtDate(from)} — ${u.fmtDate(to)}`, columns: [{ label: 'المنتج' }, { label: 'الكمية', num: true }, { label: 'المبيعات', num: true }, ...(cp ? [{ label: 'الربح', num: true }, { label: 'الهامش', num: true }] : [])], rows: top.map(p => [p.name, u.fmtQty(p.qty), u.fmtNum(p.total), ...(cp ? [u.fmtNum(p.profit), p.margin.toFixed(1) + '%'] : [])]) });
    } else if (tab === 'customers') {
      const top = ERP.reports.topCustomers(from, to, 50); const aging = ERP.reports.debtorsAging();
      box.innerHTML = kp([['users', 'primary', 'عملاء نشطون في الفترة', top.length], ['sack-dollar', 'success', 'مبيعات العملاء المسجلين', u.fmtMoney(u.sum(top, 'total'))], ['hand-holding-dollar', 'danger', 'إجمالي المديونيات', u.fmtMoney(aging.total)], ['clock', 'warning', 'ديون +60 يوم', u.fmtMoney(aging.buckets[2].total + aging.buckets[3].total)]]) + `<div class="dash-grid"><div class="card"><div class="card-header"><h3><i class="fas fa-crown"></i> أفضل 10 عملاء</h3></div><div class="card-body"><div class="chart-box"><canvas id="rp-c1"></canvas></div></div></div><div class="card"><div class="card-header"><h3><i class="fas fa-hourglass-half"></i> أعمار الديون</h3></div><div class="card-body"><div class="chart-box"><canvas id="rp-c2"></canvas></div></div></div></div><div class="card mt-4"><div class="card-header"><h3><i class="fas fa-table"></i> تفصيل العملاء</h3></div>${tbl([{ label: '#' }, { label: 'العميل' }, { label: 'الفواتير', num: true }, { label: 'المبيعات', num: true }, { label: 'متوسط الفاتورة', num: true }, ...(cp ? [{ label: 'الربح', num: true }] : []), { label: 'الرصيد الحالي', num: true }], top.map((c, i) => { const cu = ERP.crm.get(c.customerId); return [i + 1, `<a href="#/customers?id=${c.customerId}">${e(c.name)}</a>`, c.count, u.fmtNum(c.total), u.fmtNum(c.total / c.count), ...(cp ? [u.fmtNum(c.profit)] : []), cu && cu.balance > 0 ? `<span class="text-danger">${u.fmtNum(cu.balance)}</span>` : '—']; }))}</div>`;
      ERP.charts.bar('#rp-c1', { labels: top.slice(0, 10).map(c => c.name.slice(0, 16)), series: [{ label: 'المبيعات', data: top.slice(0, 10).map(c => u.round(c.total)) }], horizontal: true });
      ERP.charts.doughnut('#rp-c2', { labels: aging.buckets.map(b => b.label), data: aging.buckets.map(b => u.round(b.total)), colors: ['#16a34a', '#0891b2', '#f59e0b', '#dc2626'] });
      lastPrint = () => ERP.print.table({ title: 'تقرير العملاء', subtitle: `${u.fmtDate(from)} — ${u.fmtDate(to)}`, columns: [{ label: 'العميل' }, { label: 'الفواتير', num: true }, { label: 'المبيعات', num: true }, { label: 'الرصيد', num: true }], rows: top.map(c => [c.name, c.count, u.fmtNum(c.total), u.fmtNum((ERP.crm.get(c.customerId) || {}).balance || 0)]) });
    } else if (tab === 'profit') {
      const pl = ERP.reports.profitLoss(from, to); const months = ERP.reports.salesByMonth(12);
      box.innerHTML = kp([['sack-dollar', 'primary', 'صافي المبيعات', u.fmtMoney(pl.sales.net)], ['boxes-stacked', 'warning', 'تكلفة البضاعة', u.fmtMoney(pl.sales.cogs)], ['chart-line', 'success', 'مجمل الربح', u.fmtMoney(pl.sales.grossProfit), `${pl.sales.margin.toFixed(1)}%`], ['wallet', 'danger', 'المصروفات', u.fmtMoney(pl.expenses.total)], ['users', 'info', 'الرواتب', u.fmtMoney(pl.payroll)], ['trophy', pl.netProfit >= 0 ? 'success' : 'danger', 'صافي الربح', u.fmtMoney(pl.netProfit), `${pl.netMargin.toFixed(1)}% صافي هامش`]]) + `<div class="card"><div class="card-header"><h3><i class="fas fa-chart-column"></i> المبيعات والربح والمصروفات — 12 شهر</h3></div><div class="card-body"><div class="chart-box"><canvas id="rp-c1"></canvas></div></div></div><div class="dash-grid"><div class="card"><div class="card-header"><h3><i class="fas fa-wallet"></i> المصروفات حسب الفئة</h3></div>${tbl([{ label: 'الفئة' }, { label: 'العمليات', num: true }, { label: 'المبلغ', num: true }, { label: '%', num: true }], pl.expenses.byCategory.map(c => [e(c.name), c.count, u.fmtNum(c.total), u.pct(c.total, pl.expenses.total).toFixed(1) + '%']), ['الإجمالي', pl.expenses.count, u.fmtNum(pl.expenses.total), '100%'])}</div><div class="card"><div class="card-header"><h3><i class="fas fa-calendar"></i> شهرياً</h3></div>${tbl([{ label: 'الشهر' }, { label: 'المبيعات', num: true }, { label: 'الربح', num: true }, { label: 'المصروفات', num: true }, { label: 'الصافي', num: true }], months.map(m => [m.label, u.fmtNum(m.total), u.fmtNum(m.profit), u.fmtNum(m.expenses), `<span class="${m.profit - m.expenses < 0 ? 'text-danger' : 'text-success'}">${u.fmtNum(m.profit - m.expenses)}</span>`]))}</div></div>`;
      ERP.charts.bar('#rp-c1', { labels: months.map(m => m.label), series: [{ label: 'المبيعات', data: months.map(m => u.round(m.total)) }, { label: 'الربح', data: months.map(m => u.round(m.profit)), color: '#16a34a' }, { label: 'المصروفات', data: months.map(m => u.round(m.expenses)), color: '#dc2626' }] });
      lastPrint = () => ERP.print.table({ title: 'تقرير الأرباح والخسائر', subtitle: `${u.fmtDate(from)} — ${u.fmtDate(to)}`, columns: [{ label: 'البند' }, { label: 'المبلغ', num: true }], rows: [['صافي المبيعات', u.fmtNum(pl.sales.net)], ['تكلفة البضاعة المباعة', u.fmtNum(-pl.sales.cogs)], ['مجمل الربح', u.fmtNum(pl.sales.grossProfit)], ...pl.expenses.byCategory.map(c => [c.name, u.fmtNum(-c.total)]), ['الرواتب', u.fmtNum(-pl.payroll)], ['صافي الربح', u.fmtNum(pl.netProfit)]], summary: [{ label: 'صافي الربح', value: u.fmtMoney(pl.netProfit) }, { label: 'الهامش', value: pl.netMargin.toFixed(1) + '%' }] });
    } else if (tab === 'inventory') {
      const r = ERP.reports.inventoryReport();
      box.innerHTML = kp([['boxes-stacked', 'primary', 'الأصناف', r.rows.length], ['coins', 'success', 'قيمة المخزون', u.fmtMoney(r.totalValue)], ['tags', 'info', 'قيمة البيع المتوقعة', u.fmtMoney(r.totalRetail), `ربح متوقع ${u.fmtMoney(r.potentialProfit)}`], ['triangle-exclamation', 'warning', 'منخفض / نفذ', `${r.low} / ${r.out}`], ['snowflake', 'danger', 'بضاعة راكدة (30 يوم)', r.dead.length, u.fmtMoney(u.sum(r.dead, 'value'))]]) + `<div class="dash-grid"><div class="card"><div class="card-header"><h3><i class="fas fa-chart-pie"></i> قيمة المخزون حسب الفئة</h3></div><div class="card-body"><div class="chart-box"><canvas id="rp-c1"></canvas></div></div></div><div class="card"><div class="card-header"><h3><i class="fas fa-snowflake"></i> بضاعة راكدة</h3></div>${tbl([{ label: 'الصنف' }, { label: 'الكمية', num: true }, { label: 'القيمة', num: true }], r.dead.slice(0, 15).map(d => [e(d.product.name), u.fmtQty(d.qty), u.fmtNum(d.value)]))}</div></div><div class="card mt-4"><div class="card-header"><h3><i class="fas fa-table"></i> تقييم المخزون</h3></div>${tbl([{ label: 'الصنف' }, { label: 'الفئة' }, { label: 'الكمية', num: true }, { label: 'التكلفة', num: true }, { label: 'القيمة', num: true }, { label: 'مبيعات 30 يوم', num: true }, { label: 'تغطية', num: true }], u.sortBy(r.rows, 'value', 'desc').map(x => [e(x.product.name), e(x.category), u.fmtQty(x.qty), u.fmtNum(x.cost), u.fmtNum(x.value), u.fmtQty(x.sold30), x.daysOfCover === null ? '—' : x.daysOfCover + ' يوم']), ['الإجمالي', '', u.fmtQty(r.totalQty), '', u.fmtNum(r.totalValue), '', ''])}</div>`;
      ERP.charts.doughnut('#rp-c1', { labels: r.byCategory.map(c => c.name), data: r.byCategory.map(c => u.round(c.value)) });
      lastPrint = () => ERP.print.table({ title: 'تقرير تقييم المخزون', columns: [{ label: 'الصنف' }, { label: 'الفئة' }, { label: 'الكمية', num: true }, { label: 'التكلفة', num: true }, { label: 'القيمة', num: true }], rows: u.sortBy(r.rows, 'value', 'desc').map(x => [x.product.name, x.category, u.fmtQty(x.qty), u.fmtNum(x.cost), u.fmtNum(x.value)]), summary: [{ label: 'الأصناف', value: r.rows.length }, { label: 'القيمة', value: u.fmtMoney(r.totalValue) }] });
    } else if (tab === 'purchases') {
      const p = ERP.reports.purchasesSummary(from, to); const pos = ERP.purchasing.orders().filter(x => x.type !== 'return' && x.status !== 'cancelled' && u.inRange(x.receivedAt || x.date, from, to));
      box.innerHTML = kp([['cart-flatbed', 'primary', 'إجمالي المشتريات', u.fmtMoney(p.total), `${p.count} أمر`], ['money-bill-transfer', 'success', 'المسدد', u.fmtMoney(p.paid)], ['clock', 'danger', 'غير مسدد', u.fmtMoney(p.due)], ['truck', 'info', 'الموردون', p.bySupplier.length]]) + `<div class="dash-grid"><div class="card"><div class="card-header"><h3><i class="fas fa-truck"></i> حسب المورد</h3></div><div class="card-body"><div class="chart-box"><canvas id="rp-c1"></canvas></div></div></div><div class="card"><div class="card-header"><h3><i class="fas fa-table"></i> الموردون</h3></div>${tbl([{ label: 'المورد' }, { label: 'الأوامر', num: true }, { label: 'المبلغ', num: true }, { label: '%', num: true }], p.bySupplier.map(s => [e(s.name), s.count, u.fmtNum(s.total), u.pct(s.total, p.total).toFixed(1) + '%']))}</div></div><div class="card mt-4"><div class="card-header"><h3><i class="fas fa-list"></i> أوامر الشراء</h3></div>${tbl([{ label: 'الرقم' }, { label: 'التاريخ' }, { label: 'المورد' }, { label: 'الأصناف', num: true }, { label: 'الإجمالي', num: true }, { label: 'المتبقي', num: true }, { label: 'الحالة' }], u.sortBy(pos, 'date', 'desc').map(x => [`<a href="javascript:ERP.views.purchases.details('${x.id}')" class="num">${e(x.no)}</a>`, u.fmtDate(x.date), e(x.supplierName), x.items.length, u.fmtNum(x.total), x.due ? `<span class="text-danger">${u.fmtNum(x.due)}</span>` : '—', u.statusBadge(x.status)]))}</div>`;
      ERP.charts.doughnut('#rp-c1', { labels: p.bySupplier.map(s => s.name), data: p.bySupplier.map(s => u.round(s.total)) });
      lastPrint = () => ERP.print.table({ title: 'تقرير المشتريات', subtitle: `${u.fmtDate(from)} — ${u.fmtDate(to)}`, columns: [{ label: 'الرقم' }, { label: 'التاريخ' }, { label: 'المورد' }, { label: 'الإجمالي', num: true }, { label: 'المتبقي', num: true }], rows: pos.map(x => [x.no, u.fmtDate(x.date), x.supplierName, u.fmtNum(x.total), u.fmtNum(x.due)]), summary: [{ label: 'الإجمالي', value: u.fmtMoney(p.total) }, { label: 'غير مسدد', value: u.fmtMoney(p.due) }] });
    } else if (tab === 'tax') {
      const t = ERP.reports.taxReport(from, to); const s = ERP.settings.all();
      box.innerHTML = (s.taxEnabled ? '' : '<div class="alert alert-warning mb-4"><i class="fas fa-circle-info"></i> الضريبة غير مفعلة في الإعدادات — التقرير يعرض البيانات المسجلة فقط.</div>') + kp([['file-invoice-dollar', 'primary', 'المبيعات الخاضعة', u.fmtMoney(t.salesBase)], ['arrow-up', 'danger', 'ضريبة المخرجات (مبيعات)', u.fmtMoney(t.output)], ['arrow-down', 'success', 'ضريبة المدخلات (مشتريات)', u.fmtMoney(t.input)], ['scale-balanced', t.net >= 0 ? 'warning' : 'info', t.net >= 0 ? 'ضريبة مستحقة للسداد' : 'رصيد ضريبي دائن', u.fmtMoney(Math.abs(t.net))]]) + `<div class="card card-body"><h4 class="mb-3">تفصيل الفواتير الخاضعة للضريبة</h4>${tbl([{ label: 'الفاتورة' }, { label: 'التاريخ' }, { label: 'العميل' }, { label: 'قبل الضريبة', num: true }, { label: 'الضريبة', num: true }, { label: 'الإجمالي', num: true }], ERP.sales.range(from, to).filter(x => x.tax > 0).map(x => [`<span class="num">${e(x.no)}</span>`, u.fmtDate(x.date), e(x.customerName), u.fmtNum(x.total - x.tax), u.fmtNum(x.tax), u.fmtNum(x.total)]))}</div>`;
      lastPrint = () => ERP.print.table({ title: 'الإقرار الضريبي المبسط', subtitle: `${u.fmtDate(from)} — ${u.fmtDate(to)}`, columns: [{ label: 'البند' }, { label: 'المبلغ', num: true }], rows: [['المبيعات الخاضعة', u.fmtNum(t.salesBase)], ['ضريبة المخرجات', u.fmtNum(t.output)], ['ضريبة المدخلات', u.fmtNum(t.input)], ['صافي الضريبة', u.fmtNum(t.net)]] });
    }
  }
  function switchTab(t) { tab = t; $$('#rp-tabs .tab', el).forEach(x => x.classList.toggle('active', x.dataset.t === t)); refresh(); }
  ERP.views.reports = { refresh };
  ERP.router.register({
    id: 'reports', title: 'التقارير', icon: 'chart-pie', section: 'المالية', order: 3, perm: 'reports.view',
    render(root) {
      el = root;
      root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-chart-pie"></i> التقارير والتحليلات</h2><div class="desc">مبيعات، منتجات، عملاء، أرباح، مخزون، مشتريات، ضرائب</div></div><div class="page-actions"><div class="pills" id="rp-quick">${['today', 'week', 'month', 'lastMonth', 'quarter', 'year'].map(k => `<button class="pill ${k === 'month' ? 'active' : ''}" data-p="${k}">${ERP.reports.period(k).label}</button>`).join('')}</div><div class="flex gap-2 items-center"><input type="date" id="rp-from" value="${from}"><span class="muted">إلى</span><input type="date" id="rp-to" value="${to}"></div><button class="btn btn-primary" id="rp-print"><i class="fas fa-print"></i> طباعة</button></div></div>
        <div class="tabs" id="rp-tabs"><button class="tab active" data-t="sales"><i class="fas fa-cash-register"></i> المبيعات</button><button class="tab" data-t="products"><i class="fas fa-boxes-stacked"></i> المنتجات</button><button class="tab" data-t="customers"><i class="fas fa-users"></i> العملاء</button>${canProfit() ? '<button class="tab" data-t="profit"><i class="fas fa-chart-line"></i> الأرباح والخسائر</button>' : ''}<button class="tab" data-t="inventory"><i class="fas fa-warehouse"></i> المخزون</button><button class="tab" data-t="purchases"><i class="fas fa-cart-flatbed"></i> المشتريات</button><button class="tab" data-t="tax"><i class="fas fa-percent"></i> الضرائب</button></div><div id="rp-body"></div>`;
      $('#rp-tabs', root).onclick = ev => { const t = ev.target.closest('.tab'); if (t) switchTab(t.dataset.t); };
      $('#rp-quick', root).onclick = ev => { const b = ev.target.closest('.pill'); if (!b) return; $$('.pill', ev.currentTarget).forEach(x => x.classList.toggle('active', x === b)); const P = ERP.reports.period(b.dataset.p); $('#rp-from', root).value = P.from; $('#rp-to', root).value = P.to; refresh(); };
      $('#rp-from', root).onchange = $('#rp-to', root).onchange = () => { $$('#rp-quick .pill', root).forEach(x => x.classList.remove('active')); refresh(); };
      $('#rp-print', root).onclick = () => lastPrint && lastPrint();
    },
    onShow(root, params) { if (params.tab) switchTab(params.tab); else refresh(); },
  });
})();
