/* ==========================================================================
   View: Sales — invoices list, invoice detail, returns, payments, quotations
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el, table, period = 'month', from = '', to = '';
  const S = () => ERP.db.collection('sales');

  function rows() { const P = period === 'custom' ? { from, to } : ERP.reports.period(period); return u.sortBy(S().all().filter(s => u.inRange(s.date, P.from, P.to)), 'date', 'desc'); }
  function refresh() { if (!table) return; const r = rows(); table.setRows(r); const sales = r.filter(s => s.type === 'sale' && s.status !== 'void'); const rets = r.filter(s => s.type === 'return'); $('#s-kpis', el).innerHTML = [['receipt', 'primary', 'الفواتير', u.fmtInt(sales.length)], ['sack-dollar', 'success', 'إجمالي المبيعات', u.fmtMoney(u.sum(sales, 'total'))], ['rotate-left', 'warning', 'مرتجعات', `${u.fmtMoney(u.sum(rets, 'total'))} (${rets.length})`], ['hand-holding-dollar', 'danger', 'غير محصّل', u.fmtMoney(u.sum(sales, 'due'))], ...(ERP.auth.can('reports.profit') ? [['chart-line', 'purple', 'الربح', u.fmtMoney(u.sum(sales, 'profit') - u.sum(rets, s => s.total - s.tax - s.cogs))]] : [])].map(k => `<div class="card kpi"><div class="kpi-icon ${k[1]}"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.2rem">${k[3]}</div></div></div>`).join(''); }

  function viewInvoice(id) {
    const s = S().get(id); if (!s) return ERP.ui.error('الفاتورة غير موجودة');
    const isRet = s.type === 'return';
    const canRet = !isRet && (ERP.auth.can('pos.return') || ERP.settings.get('approvalRequireReturn')) && s.status !== 'void' && s.status !== 'returned';
    const canVoid = (ERP.auth.can('pos.void') || ERP.settings.get('approvalRequireVoid')) && ERP.sales.canVoid(s);
    const canPay = !isRet && s.due > 0 && s.customerId && ERP.auth.can('customers.receipt') && s.status !== 'void';
    const rets = isRet ? [] : S().where({ refSaleId: id });
    const h = ERP.ui.view(`${isRet ? 'مرتجع' : 'فاتورة'} <span class="num">${e(s.no)}</span> ${u.statusBadge(s.status)}`, `
      <div class="detail-grid mb-3">
        <div class="detail-item"><div class="dl">التاريخ</div><div class="dv num">${u.fmtDateTime(s.date)}</div></div>
        <div class="detail-item"><div class="dl">العميل</div><div class="dv">${s.customerId ? `<a href="#/customers?id=${s.customerId}">${e(s.customerName)}</a>` : e(s.customerName)}</div></div>
        <div class="detail-item"><div class="dl">الكاشير</div><div class="dv">${e(s.userName || '—')}</div></div>
        <div class="detail-item"><div class="dl">الدفع</div><div class="dv">${(s.payments || []).map(p => `${e(ERP.sales.methodName(p.method))} ${u.fmtNum(p.amount)}`).join(' + ') || '—'}</div></div>
        ${isRet ? `<div class="detail-item"><div class="dl">الفاتورة الأصلية</div><div class="dv"><a href="javascript:ERP.views.sales.viewInvoice('${s.refSaleId}')">${e(s.refNo)}</a></div></div><div class="detail-item"><div class="dl">السبب</div><div class="dv">${e(s.reason || '—')}</div></div>` : ''}
        ${s.status === 'void' ? `<div class="detail-item" style="grid-column:1/-1"><div class="alert alert-danger"><i class="fas fa-ban"></i> ملغاة ${u.fmtDateTime(s.voidedAt)} — ${e(s.voidReason || '')}${s.voidApprovedBy ? ` · اعتماد: ${e(s.voidApprovedBy)}` : ''}</div></div>` : ''}
        ${ERP.eta && (s.etaStatus || ERP.eta.canResend(s)) ? `<div class="detail-item" style="grid-column:1/-1"><div class="dl">الإيصال الإلكتروني (الضرائب)</div><div class="dv">${ERP.eta.badge(s)} ${s.etaUUID ? `<span class="num text-xs" style="direction:ltr;word-break:break-all">${e(s.etaUUID)}</span>` : ''}${s.etaError ? `<div class="text-danger text-sm">${e(s.etaError)}</div>` : ''}${ERP.eta.canResend(s) ? ` <button class="btn btn-sm btn-soft-danger" onclick="ERP.views.sales.etaResend('${s.id}')"><i class="fas fa-rotate"></i> إعادة الإرسال</button>` : ''}</div></div>` : ''}
        ${s.approvedBy ? `<div class="detail-item"><div class="dl">اعتماد مشرف</div><div class="dv"><i class="fas fa-user-shield text-primary"></i> ${e(s.approvedBy.name)}</div></div>` : ''}
      </div>
      <div class="table-wrap"><table class="table table-compact"><thead><tr><th>الصنف</th><th class="num">الكمية</th><th class="num">السعر</th><th class="num">الخصم</th>${s.tax ? '<th class="num">الضريبة</th>' : ''}<th class="num">الإجمالي</th>${!isRet && s.returnedQty && Object.keys(s.returnedQty).length ? '<th class="num">مرتجع</th>' : ''}</tr></thead><tbody>${s.items.map(it => `<tr><td>${e(it.name)}${it.promoLabel ? ` <span class="badge badge-danger">${e(it.promoLabel)}</span>` : ''}</td><td class="num">${u.fmtQty(it.qty)}</td><td class="num">${u.fmtNum(it.price)}</td><td class="num">${it.discount ? u.fmtNum(it.discount) : '—'}</td>${s.tax ? `<td class="num">${u.fmtNum(it.taxAmount)}</td>` : ''}<td class="num fw-700">${u.fmtNum(it.total)}</td>${!isRet && s.returnedQty && Object.keys(s.returnedQty).length ? `<td class="num text-warning">${s.returnedQty[ERP.units.lineKey(it)] ? u.fmtQty(s.returnedQty[ERP.units.lineKey(it)]) : ''}</td>` : ''}</tr>`).join('')}</tbody></table></div>
      <div class="doc-summary"><div class="doc-summary-box"><div class="tot-row"><span>الإجمالي</span><span class="val">${u.fmtNum(s.subtotal)}</span></div>${s.discount ? `<div class="tot-row"><span>الخصم</span><span class="val text-danger">-${u.fmtNum(s.discount)}</span></div>` : ''}${s.tax ? `<div class="tot-row"><span>الضريبة</span><span class="val">${u.fmtNum(s.tax)}</span></div>` : ''}${s.loyaltyDiscount ? `<div class="tot-row"><span>نقاط ولاء</span><span class="val text-success">-${u.fmtNum(s.loyaltyDiscount)}</span></div>` : ''}<div class="tot-row grand"><span>الصافي</span><span class="val">${u.fmtMoney(s.total)}</span></div><div class="tot-row"><span>المدفوع</span><span class="val">${u.fmtNum(s.paid)}</span></div>${s.due > 0 ? `<div class="tot-row"><span class="text-danger fw-700">المتبقي</span><span class="val text-danger">${u.fmtNum(s.due)}</span></div>` : ''}${s.change ? `<div class="tot-row"><span>الباقي للعميل</span><span class="val">${u.fmtNum(s.change)}</span></div>` : ''}${ERP.auth.can('reports.profit') && !isRet ? `<div class="tot-row"><span class="muted">الربح</span><span class="val text-success">${u.fmtNum(s.profit)}</span></div>` : ''}</div></div>
      ${rets.length ? `<div class="mt-3"><strong class="text-sm">المرتجعات:</strong> ${rets.map(r => `<a href="javascript:ERP.views.sales.viewInvoice('${r.id}')" class="badge badge-purple num">${e(r.no)} — ${u.fmtMoney(r.total)}</a>`).join(' ')}</div>` : ''}
      ${s.notes ? `<div class="alert alert-info mt-3"><i class="fas fa-note-sticky"></i> ${e(s.notes)}</div>` : ''}`,
      { size: 'lg', footer: `<button class="btn" data-a="close">إغلاق</button><div class="flex-1"></div>${canVoid ? `<button class="btn btn-soft-danger" data-a="void"><i class="fas fa-ban"></i> إلغاء</button>` : ''}${canRet ? `<button class="btn btn-soft-warning" data-a="ret"><i class="fas fa-rotate-left"></i> مرتجع</button>` : ''}${canPay ? `<button class="btn btn-soft-success" data-a="pay"><i class="fas fa-hand-holding-dollar"></i> تحصيل</button>` : ''}${ERP.invoiceShare && s.status !== 'void' ? '<button class="btn btn-soft-success" data-a="wa"><i class="fab fa-whatsapp"></i> إرسال للعميل واتساب</button>' : ''}<button class="btn btn-outline" data-a="a4"><i class="fas fa-file-invoice"></i> A4</button><button class="btn btn-primary" data-a="print"><i class="fas fa-print"></i> إيصال</button>` });
    h.$('[data-a=close]').onclick = () => h.close(); h.$('[data-a=print]').onclick = () => ERP.print.receipt(s); h.$('[data-a=a4]').onclick = () => ERP.print.invoice(s); const wa = h.$('[data-a=wa]'); if (wa) wa.onclick = () => { h.close(); ERP.invoiceShare.dialog(s); };
    if (canVoid) h.$('[data-a=void]').onclick = async () => { const r = await ERP.ui.prompt('سبب الإلغاء', { title: 'إلغاء الفاتورة' }); if (r === null) return; let approver = null; if (ERP.settings.get('approvalRequireVoid') || !ERP.auth.can('pos.void')) { const ap = await ERP.auth.approve({ reason: `إلغاء الفاتورة ${s.no} (${u.fmtMoney(s.total)})` }); if (!ap.ok) return; approver = ap.self ? null : ap.approver; } try { ERP.sales.void(id, r, approver || (ERP.auth.can('pos.void') ? null : ERP.auth.current())); h.close(); ERP.ui.success('تم الإلغاء'); } catch (err) { ERP.ui.error(err.message); } };
    if (canRet) h.$('[data-a=ret]').onclick = () => { h.close(); returnDialog(id); };
    if (canPay) h.$('[data-a=pay]').onclick = () => { h.close(); ERP.views.customers.receiptDialog(s.customerId, s.id); };
  }

  async function returnDialog(saleId = null) {
    let approver = null;
    if (!ERP.auth.can('pos.return') || ERP.settings.get('approvalRequireReturn')) { const ap = await ERP.auth.approve({ reason: 'عمل مرتجع بيع' }); if (!ap.ok) return; approver = ap.self ? null : ap.approver; }
    if (!saleId) { const no = await ERP.ui.prompt('رقم الفاتورة الأصلية', { title: 'مرتجع', placeholder: ERP.settings.prefix('sale') + '-000001' }); if (!no) return; const s = ERP.sales.byNo(no.trim()) || ERP.sales.byNo(no.trim().toUpperCase()); if (!s) return ERP.ui.error('الفاتورة غير موجودة'); saleId = s.id; }
    const s = S().get(saleId); if (s.type !== 'sale' || s.status === 'void') return ERP.ui.error('لا يمكن الإرجاع من هذه الفاتورة');
    const avail = s.items.map(it => ({ ...it, avail: u.round(it.qty - u.num((s.returnedQty || {})[ERP.units.lineKey(it)]), 3) })).filter(it => it.avail > 0);
    if (!avail.length) return ERP.ui.warn('تم إرجاع كل أصناف الفاتورة');
    const methods = ERP.sales.methods();
    const h = ERP.ui.modal({ title: `مرتجع من ${e(s.no)}`, icon: 'rotate-left', size: 'lg', body: `<div class="alert alert-info mb-3"><i class="fas fa-circle-info"></i> ${e(s.customerName)} — ${u.fmtDateTime(s.date)} — ${u.fmtMoney(s.total)}${s.due ? ` (متبقي آجل ${u.fmtMoney(s.due)} سيُخصم أولاً)` : ''}</div><div class="table-wrap"><table class="table table-compact"><thead><tr><th style="width:36px"><input type="checkbox" id="r-all"></th><th>الصنف</th><th class="num">المباع</th><th class="num">المتاح</th><th class="num" style="width:120px">إرجاع</th><th class="num">القيمة</th></tr></thead><tbody>${avail.map((it, i) => `<tr><td><input type="checkbox" class="r-chk" data-i="${i}"></td><td>${e(it.name)}</td><td class="num">${u.fmtQty(it.qty)}</td><td class="num">${u.fmtQty(it.avail)}</td><td><input type="number" step="any" min="0" max="${it.avail}" class="r-qty num" data-i="${i}" value="0" style="min-height:32px"></td><td class="num r-val" data-i="${i}">0.00</td></tr>`).join('')}</tbody></table></div><div class="form-row cols-2 mt-3"><div class="form-group"><label>طريقة رد المبلغ</label><select id="r-method">${methods.filter(m => !m.isCredit).map(m => `<option value="${m.id}">${e(m.name)}</option>`).join('')}${s.customerId ? '<option value="credit">رصيد للعميل (خصم من مديونيته)</option>' : ''}</select></div><div class="form-group"><label class="required">السبب</label><select id="r-reason"><option>منتج معيب</option><option>منتهي الصلاحية</option><option>خطأ في الطلب</option><option>عدم رضا العميل</option><option>أخرى</option></select></div></div><div class="tot-row grand"><span>إجمالي المرتجع</span><span class="val" id="r-total">0.00</span></div>`, footer: `<button class="btn" data-a="c">إلغاء</button><button class="btn btn-warning" data-a="ok"><i class="fas fa-check"></i> تنفيذ المرتجع</button>` });
    const calc = () => { let tot = 0; h.$$('.r-qty').forEach(inp => { const i = +inp.dataset.i; const q = u.clamp(u.num(inp.value), 0, avail[i].avail); const v = u.round(q / avail[i].qty * avail[i].total); h.$(`.r-val[data-i="${i}"]`).textContent = u.fmtNum(v); tot += v; }); h.$('#r-total').textContent = u.fmtNum(tot); };
    h.body.addEventListener('input', ev => { if (ev.target.classList.contains('r-qty')) { const chk = h.$(`.r-chk[data-i="${ev.target.dataset.i}"]`); chk.checked = u.num(ev.target.value) > 0; calc(); } });
    h.body.addEventListener('change', ev => { if (ev.target.classList.contains('r-chk')) { const q = h.$(`.r-qty[data-i="${ev.target.dataset.i}"]`); q.value = ev.target.checked ? avail[+ev.target.dataset.i].avail : 0; calc(); } if (ev.target.id === 'r-all') { h.$$('.r-chk').forEach(c => { c.checked = ev.target.checked; h.$(`.r-qty[data-i="${c.dataset.i}"]`).value = ev.target.checked ? avail[+c.dataset.i].avail : 0; }); calc(); } });
    h.$('[data-a=c]').onclick = () => h.close();
    h.$('[data-a=ok]').onclick = () => { const lines = h.$$('.r-qty').map(inp => ({ productId: avail[+inp.dataset.i].productId, unitId: ERP.units.lineUnit(avail[+inp.dataset.i]), qty: u.num(inp.value) })).filter(l => l.qty > 0); if (!lines.length) return ERP.ui.warn('حدد كميات للإرجاع'); try { const r = ERP.sales.createReturn({ saleId, lines, refundMethod: h.$('#r-method').value, reason: h.$('#r-reason').value, approvedBy: approver || (ERP.auth.can('pos.return') ? null : ERP.auth.current()) }); h.close(); ERP.ui.success(`تم المرتجع ${r.no} — ${u.fmtMoney(r.total)}`); ERP.print.receipt(r); } catch (err) { ERP.ui.error(err.message); } };
  }

  async function etaResend(id) { try { const r = await ERP.eta.resend(id); ERP.ui.success(r === 'rebuilt' ? 'أُعيد بناء الإيصال (UUID جديد يشير للقديم) وأُضيف لقائمة الإرسال' : r === 'noop' ? 'الإيصال مُرسل بالفعل' : 'أُضيف لقائمة الإرسال للضرائب'); refresh(); } catch (err) { ERP.ui.error(err.message); } }
  ERP.views.sales = { viewInvoice, returnDialog, refresh, etaResend };
  ERP.ui.cmdk.addAction({ icon: 'rotate-left', title: 'عمل مرتجع', keywords: 'return مرتجع', perm: 'pos.return', run: () => returnDialog() });
  ERP.router.register({
    id: 'sales', title: 'الفواتير والمبيعات', icon: 'file-invoice-dollar', section: 'العمليات', order: 4, perm: 'sales.view',
    render(root) {
      el = root;
      root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-file-invoice-dollar"></i> الفواتير والمبيعات</h2><div class="desc">سجل كامل للفواتير والمرتجعات</div></div>
        <div class="page-actions"><div class="pills" id="s-period">${['today', 'week', 'month', 'year', 'all'].map(k => `<button class="pill ${k === period ? 'active' : ''}" data-p="${k}">${ERP.reports.period(k).label}</button>`).join('')}<button class="pill" data-p="custom">مخصص</button></div><div id="s-custom" class="flex gap-2 hidden"><input type="date" id="s-from"><input type="date" id="s-to"></div>${ERP.auth.can('pos.return') ? '<button class="btn btn-outline" id="s-ret"><i class="fas fa-rotate-left"></i> مرتجع</button>' : ''}${ERP.auth.can('pos.use') ? '<button class="btn btn-primary" onclick="ERP.router.go(\'pos\')"><i class="fas fa-cash-register"></i> بيع جديد</button>' : ''}</div></div>
        <div class="kpi-grid mb-4" id="s-kpis"></div><div id="s-table"></div>`;
      table = ERP.ui.table({ el: '#s-table', rows: [], exportName: 'المبيعات', exportPerm: 'sales.export', defaultSort: { key: 'date', dir: 'desc' }, toolbarExtra: `<select id="s-status" style="min-width:150px"><option value="">كل الحالات</option><option value="paid">مدفوعة</option><option value="partial">جزئي</option><option value="unpaid">غير مدفوعة</option><option value="return">مرتجعات</option><option value="void">ملغاة</option></select>`, columns: [
        { key: 'no', label: 'الرقم', render: (s, t) => `<strong class="num">${u.highlight(s.no, t)}</strong>${s.type === 'return' ? ' ' + u.badge('مرتجع', 'purple') : ''}${s.hasReturns ? ' <i class="fas fa-rotate-left text-warning text-xs" title="عليها مرتجعات"></i>' : ''}`, text: s => s.no },
        { key: 'date', label: 'التاريخ', render: s => `<span class="num text-sm">${u.fmtDateTime(s.date)}</span>`, text: s => u.fmtDateTime(s.date) },
        { key: 'customerName', label: 'العميل', render: (s, t) => u.highlight(s.customerName, t) },
        { id: 'items', label: 'الأصناف', num: true, render: s => s.items.length, sortValue: s => s.items.length, text: s => s.items.length },
        { key: 'total', label: 'الصافي', num: true, render: s => `<strong class="${s.type === 'return' ? 'text-warning' : ''}">${s.type === 'return' ? '-' : ''}${u.fmtNum(s.total)}</strong>`, text: s => u.fmtNum(s.total), footer: r => u.fmtMoney(u.sum(r.filter(s => s.type === 'sale' && s.status !== 'void'), 'total') - u.sum(r.filter(s => s.type === 'return'), 'total')) },
        { key: 'paid', label: 'المدفوع', num: true, render: s => u.fmtNum(s.paid) },
        { key: 'due', label: 'المتبقي', num: true, render: s => s.due > 0 ? `<span class="text-danger fw-700">${u.fmtNum(s.due)}</span>` : '—', footer: r => `<span class="text-danger">${u.fmtMoney(u.sum(r.filter(s => s.status !== 'void'), 'due'))}</span>` },
        { id: 'pm', label: 'الدفع', sortable: false, render: s => (s.payments || []).map(p => u.badge(ERP.sales.methodName(p.method), p.isCredit ? 'warning' : 'neutral')).join(' '), text: s => (s.payments || []).map(p => ERP.sales.methodName(p.method)).join('+') },
        { key: 'status', label: 'الحالة', render: s => u.statusBadge(s.status), text: s => s.status },
        ...(ERP.eta && ERP.settings.get('etaEnabled') ? [{ id: 'eta', label: 'الضرائب', sortable: false, render: s => ERP.eta.badge(s), text: s => s.etaStatus || '' }] : []),
        { key: 'userName', label: 'الكاشير', render: s => `<span class="text-sm">${e(s.userName || '—')}</span>` },
        { id: 'a', label: '', sortable: false, export: false, class: 'actions', render: s => `<button class="btn btn-icon btn-sm btn-ghost" data-v="${s.id}"><i class="fas fa-eye"></i></button><button class="btn btn-icon btn-sm btn-ghost" data-pr="${s.id}"><i class="fas fa-print"></i></button>${ERP.invoiceShare && s.status !== 'void' ? `<button class="btn btn-icon btn-sm btn-ghost text-success" data-wa="${s.id}" title="إرسال للعميل واتساب"><i class="fab fa-whatsapp"></i></button>` : ''}${ERP.eta && ERP.eta.canResend(s) ? `<button class="btn btn-icon btn-sm btn-ghost text-danger" data-eta="${s.id}" title="إعادة الإرسال للضرائب"><i class="fas fa-rotate"></i></button>` : ''}` },
      ], rowClass: s => s.status === 'void' ? 'muted' : '', onRowClick: s => viewInvoice(s.id) });
      $('#s-period', root).onclick = ev => { const b = ev.target.closest('.pill'); if (!b) return; period = b.dataset.p; $$('.pill', ev.currentTarget).forEach(x => x.classList.toggle('active', x === b)); $('#s-custom', root).classList.toggle('hidden', period !== 'custom'); if (period !== 'custom') refresh(); };
      $('#s-from', root).onchange = $('#s-to', root).onchange = () => { from = $('#s-from', root).value; to = $('#s-to', root).value; refresh(); };
      $('#s-status', root).onchange = ev => { const v = ev.target.value; table.setRows(rows().filter(s => !v || (v === 'return' ? s.type === 'return' : s.type === 'sale' && s.status === v))); };
      root.addEventListener('click', ev => { const x = ev.target.closest('[data-eta]'); if (x) { ev.stopPropagation(); etaResend(x.dataset.eta); return; } const v = ev.target.closest('[data-v]'), p = ev.target.closest('[data-pr]'); if (v) { ev.stopPropagation(); viewInvoice(v.dataset.v); } if (p) { ev.stopPropagation(); ERP.print.sale(S().get(p.dataset.pr)); } const w = ev.target.closest('[data-wa]'); if (w) { ev.stopPropagation(); ERP.invoiceShare.dialog(w.dataset.wa); } });
      const rb = $('#s-ret', root); if (rb) rb.onclick = () => returnDialog();
    },
    onShow(root, params) { refresh(); if (params.id) viewInvoice(params.id); },
  });
  ERP.bus.on('db:change', u.debounce(ev => { if (table && ERP.router.current() === 'sales' && ev?.collection === 'sales') refresh(); }, 250));
})();
