/* ==========================================================================
   View: Suppliers
   ========================================================================== */
window.ERP = window.ERP || {}; ERP.views = ERP.views || {};
(function () {
  const u = ERP.utils; const e = u.escapeHtml;
  let el, table;
  function refresh() { if (!table) return; const l = ERP.purchasing.suppliers(); table.setRows(l); $('#sp-kpis', el).innerHTML = [['truck', 'primary', 'الموردون', u.fmtInt(l.filter(s => s.active !== false).length)], ['money-bill-transfer', 'danger', 'مستحقات للموردين', u.fmtMoney(u.sum(l.filter(s => s.balance > 0), 'balance'))], ['file-invoice', 'info', 'أوامر شراء مفتوحة', u.fmtInt(ERP.purchasing.orders().filter(p => p.status === 'ordered').length)]].map(k => `<div class="card kpi"><div class="kpi-icon ${k[1]}"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.2rem">${k[3]}</div></div></div>`).join(''); }
  async function openForm(id = null) {
    if (!ERP.auth.require('suppliers.manage')) return;
    const s = id ? ERP.purchasing.supplier(id) : null;
    const r = await ERP.ui.form({ title: s ? `تعديل مورد — ${e(s.name)}` : 'مورد جديد', icon: 'truck', size: 'lg', values: s || {}, fields: [{ name: 'name', label: 'اسم المورد / الشركة', required: true }, { name: 'contact', label: 'اسم المسؤول' }, { name: 'phone', label: 'الهاتف', type: 'tel' }, { name: 'email', label: 'البريد', type: 'email' }, { name: 'address', label: 'العنوان', cols: 2 }, { name: 'taxNumber', label: 'الرقم الضريبي' }, { name: 'paymentTerms', label: 'مدة السداد (يوم)', type: 'number', min: 0 }, ...(!s ? [{ name: 'openingBalance', label: 'رصيد مستحق افتتاحي', type: 'number', min: 0, step: 'any' }] : []), { name: 'notes', label: 'ملاحظات', type: 'textarea', cols: 2 }, ...(s ? [{ name: 'active', type: 'checkbox', checkLabel: 'نشط' }] : [])], onSubmit: d => s ? ERP.purchasing.updateSupplier(id, d) : ERP.purchasing.createSupplier(d) });
    if (r) ERP.ui.success('تم الحفظ');
  }
  async function payDialog(supplierId, poId = null) {
    if (!ERP.auth.require('purchases.pay')) return;
    const s = ERP.purchasing.supplier(supplierId); const po = poId ? ERP.purchasing.order(poId) : null;
    const methods = ERP.sales.methods().filter(m => !m.isCredit);
    const r = await ERP.ui.form({ title: `سداد للمورد ${e(s.name)}`, icon: 'money-bill-transfer', fields: [{ name: 'i', type: 'html', cols: 2, html: `<div class="alert alert-warning"><i class="fas fa-circle-info"></i> المستحق للمورد: <strong>${u.fmtMoney(s.balance)}</strong>${po ? ` · متبقي ${e(po.no)}: <strong>${u.fmtMoney(po.due)}</strong>` : ''}</div>` }, { name: 'amount', label: 'المبلغ', type: 'number', step: 'any', min: 0.01, required: true, value: po ? po.due : s.balance }, { name: 'method', label: 'طريقة الدفع', type: 'select', options: methods.map(m => `<option value="${m.id}">${e(m.name)}</option>`).join('') }, { name: 'date', label: 'التاريخ', type: 'date', value: u.todayISO() }, { name: 'notes', label: 'ملاحظات / رقم الشيك' }], submitText: 'سداد', onSubmit: d => ERP.purchasing.paySupplier({ supplierId, amount: d.amount, method: d.method, notes: d.notes, poId, date: d.date ? new Date(d.date + 'T12:00:00').toISOString() : null }) });
    if (r) ERP.ui.success(`تم السداد ${u.fmtMoney(r.amount)}`);
  }
  function details(id) {
    const s = ERP.purchasing.supplier(id); const stm = ERP.purchasing.statement(id); const perf = ERP.purchasing.performance(id);
    const pos = u.sortBy(ERP.purchasing.orders().filter(p => p.supplierId === id), 'date', 'desc').slice(0, 50);
    const prods = ERP.db.collection('products').where({ supplierId: id });
    const h = ERP.ui.view(`<div class="flex items-center gap-3"><div class="avatar lg" style="background:var(--info-bg);color:var(--info)"><i class="fas fa-truck"></i></div><div>${e(s.name)} ${s.active === false ? u.badge('موقوف', 'neutral') : ''}<div class="text-sm muted num fw-500">${e(s.code)} · ${e(s.phone || '')} ${s.contact ? '· ' + e(s.contact) : ''}</div></div></div>`, `
      <div class="kpi-grid mb-4">${[['money-bill-transfer', s.balance > 0 ? 'danger' : 'success', 'المستحق له', u.fmtMoney(s.balance)], ['file-invoice', 'primary', 'أوامر الشراء', perf.orders], ['sack-dollar', 'info', 'إجمالي المشتريات', u.fmtMoney(perf.total)], ['clock', perf.late ? 'warning' : 'success', 'الالتزام بالمواعيد', perf.received ? `${perf.onTime}/${perf.received} في الموعد` : '—'], ['boxes-stacked', 'purple', 'منتجات مرتبطة', prods.length]].map(k => `<div class="card kpi" style="padding:.8rem 1rem"><div class="kpi-icon ${k[1]}" style="width:42px;height:42px;font-size:1.1rem"><i class="fas fa-${k[0]}"></i></div><div class="kpi-body"><div class="kpi-label">${k[2]}</div><div class="kpi-value" style="font-size:1.1rem">${k[3]}</div></div></div>`).join('')}</div>
      <div class="tabs"><button class="tab active" data-t="stm">كشف الحساب</button><button class="tab" data-t="po">أوامر الشراء</button><button class="tab" data-t="pr">المنتجات</button></div>
      <div class="tab-pane active" data-p="stm"><div class="table-wrap" style="max-height:360px;overflow:auto"><table class="table table-compact"><thead><tr><th>التاريخ</th><th>النوع</th><th>المرجع</th><th class="num">مدين (سداد)</th><th class="num">دائن (شراء)</th><th class="num">الرصيد</th></tr></thead><tbody>${stm.opening ? `<tr><td colspan="5">رصيد افتتاحي</td><td class="num">${u.fmtNum(stm.opening)}</td></tr>` : ''}${stm.rows.slice().reverse().map(r => `<tr><td class="num">${u.fmtDate(r.date)}</td><td>${e(r.type)}</td><td class="num">${e(r.ref)}</td><td class="num text-success">${r.debit ? u.fmtNum(r.debit) : ''}</td><td class="num">${r.credit ? u.fmtNum(r.credit) : ''}</td><td class="num fw-700">${u.fmtNum(r.balance)}</td></tr>`).join('') || '<tr><td colspan="6" class="text-center muted">لا حركات</td></tr>'}</tbody></table></div></div>
      <div class="tab-pane" data-p="po"><div class="table-wrap" style="max-height:360px;overflow:auto"><table class="table table-compact"><thead><tr><th>الرقم</th><th>التاريخ</th><th class="num">الإجمالي</th><th class="num">المتبقي</th><th>الحالة</th></tr></thead><tbody>${pos.map(p => `<tr class="cursor-pointer" onclick="ERP.views.purchases.details('${p.id}')"><td class="num">${e(p.no)}${p.type === 'return' ? ' ' + u.badge('مرتجع', 'purple') : ''}</td><td class="num">${u.fmtDate(p.date)}</td><td class="num">${u.fmtNum(p.total)}</td><td class="num text-danger">${p.due ? u.fmtNum(p.due) : ''}</td><td>${u.statusBadge(p.status)}</td></tr>`).join('') || '<tr><td colspan="5" class="text-center muted">لا أوامر</td></tr>'}</tbody></table></div></div>
      <div class="tab-pane" data-p="pr"><div class="table-wrap" style="max-height:360px;overflow:auto"><table class="table table-compact"><thead><tr><th>المنتج</th><th class="num">التكلفة</th><th class="num">السعر</th><th class="num">المخزون</th></tr></thead><tbody>${prods.map(p => `<tr><td>${e(p.name)}</td><td class="num">${u.fmtNum(p.cost)}</td><td class="num">${u.fmtNum(p.price)}</td><td class="num">${u.fmtQty(p.stock)} ${u.stockBadge(p)}</td></tr>`).join('') || '<tr><td colspan="4" class="text-center muted">لا منتجات</td></tr>'}</tbody></table></div></div>`,
      { size: 'xl', footer: `<button class="btn" data-a="close">إغلاق</button><div class="flex-1"></div><button class="btn btn-outline" data-a="stm"><i class="fas fa-print"></i> كشف حساب</button>${ERP.auth.can('purchases.manage') ? `<button class="btn btn-outline" data-a="po"><i class="fas fa-plus"></i> أمر شراء</button>` : ''}${ERP.auth.can('purchases.pay') && s.balance > 0 ? `<button class="btn btn-success" data-a="pay"><i class="fas fa-money-bill-transfer"></i> سداد</button>` : ''}${ERP.auth.can('suppliers.manage') ? `<button class="btn btn-primary" data-a="edit"><i class="fas fa-pen"></i> تعديل</button>` : ''}` });
    h.el.querySelector('.tabs').onclick = ev => { const t = ev.target.closest('.tab'); if (!t) return; h.$$('.tab').forEach(x => x.classList.toggle('active', x === t)); h.$$('.tab-pane').forEach(x => x.classList.toggle('active', x.dataset.p === t.dataset.t)); };
    h.$('[data-a=close]').onclick = () => h.close(); h.$('[data-a=stm]').onclick = () => ERP.print.statement({ title: 'كشف حساب مورد', party: s, rows: stm.rows.map(r => ({ ...r, debit: r.credit, credit: r.debit })), opening: stm.opening });
    const po = h.$('[data-a=po]'); if (po) po.onclick = () => { h.close(); ERP.views.purchases.openForm(null, { supplierId: id }); };
    const pay = h.$('[data-a=pay]'); if (pay) pay.onclick = () => { h.close(); payDialog(id); };
    const ed = h.$('[data-a=edit]'); if (ed) ed.onclick = () => { h.close(); openForm(id); };
  }
  ERP.views.suppliers = { openForm, payDialog, details };
  ERP.router.register({
    id: 'suppliers', title: 'الموردون', icon: 'truck', section: 'الأطراف', order: 2, perm: ['suppliers.manage', 'purchases.view'],
    render(root) {
      el = root; const canM = ERP.auth.can('suppliers.manage'), canP = ERP.auth.can('purchases.pay');
      root.innerHTML = `<div class="page-header"><div><h2><i class="fas fa-truck"></i> الموردون</h2><div class="desc">بيانات الموردين، المستحقات، الأداء والسداد</div></div><div class="page-actions">${ERP.cheques ? '<button class="btn btn-outline" id="sp-aging"><i class="fas fa-clock"></i> أعمار الديون والاستحقاقات</button>' : ''}<button class="btn btn-outline" id="sp-print"><i class="fas fa-print"></i> تقرير المستحقات</button>${canM ? '<button class="btn btn-primary" id="sp-add"><i class="fas fa-plus"></i> مورد جديد</button>' : ''}</div></div><div class="kpi-grid mb-4" id="sp-kpis"></div><div id="sp-table"></div>`;
      table = ERP.ui.table({ el: '#sp-table', rows: [], exportName: 'الموردون', defaultSort: { key: 'balance', dir: 'desc' }, columns: [
        { key: 'name', label: 'المورد', render: (s, t) => `<div class="fw-600">${u.highlight(s.name, t)}</div><div class="text-xs muted">${u.highlight(s.code, t)}${s.contact ? ' · ' + e(s.contact) : ''}</div>`, text: s => s.name + ' ' + s.code },
        { key: 'phone', label: 'الهاتف', render: (s, t) => `<span class="num">${u.highlight(s.phone || '—', t)}</span>` },
        { key: 'balance', label: 'المستحق له', num: true, render: s => s.balance > 0 ? `<strong class="text-danger">${u.fmtNum(s.balance)}</strong>` : '—', footer: r => `<span class="text-danger">${u.fmtMoney(u.sum(r.filter(s => s.balance > 0), 'balance'))}</span>` },
        { id: 'po', label: 'أوامر الشراء', num: true, render: s => ERP.purchasing.orders().filter(p => p.supplierId === s.id && p.type !== 'return').length, sortValue: s => ERP.purchasing.orders().filter(p => p.supplierId === s.id).length, text: s => ERP.purchasing.orders().filter(p => p.supplierId === s.id).length },
        { id: 'pr', label: 'المنتجات', num: true, render: s => ERP.db.collection('products').where({ supplierId: s.id }).length, sortable: false, text: s => ERP.db.collection('products').where({ supplierId: s.id }).length },
        { key: 'paymentTerms', label: 'مدة السداد', render: s => s.paymentTerms ? `${s.paymentTerms} يوم` : '—' },
        { key: 'lastActivityAt', label: 'آخر تعامل', render: s => `<span class="text-xs muted">${s.lastActivityAt ? u.relTime(s.lastActivityAt) : '—'}</span>` },
        { id: 'a', label: '', sortable: false, export: false, class: 'actions', render: s => `<button class="btn btn-icon btn-sm btn-ghost" data-a="view" data-id="${s.id}"><i class="fas fa-eye"></i></button>${canP && s.balance > 0 ? `<button class="btn btn-icon btn-sm btn-soft-success" data-a="pay" data-id="${s.id}" data-tip="سداد"><i class="fas fa-money-bill-transfer"></i></button>` : ''}${canM ? `<button class="btn btn-icon btn-sm btn-ghost" data-a="edit" data-id="${s.id}"><i class="fas fa-pen"></i></button><button class="btn btn-icon btn-sm btn-ghost text-danger" data-a="del" data-id="${s.id}"><i class="fas fa-trash"></i></button>` : ''}` },
      ], rowClass: s => s.active === false ? 'muted' : '', onRowClick: s => details(s.id) });
      root.addEventListener('click', async ev => { const b = ev.target.closest('[data-a][data-id]'); if (!b) return; ev.stopPropagation(); const { a, id } = b.dataset; if (a === 'view') details(id); if (a === 'edit') openForm(id); if (a === 'pay') payDialog(id); if (a === 'del') { const s = ERP.purchasing.supplier(id); if (await ERP.ui.confirm(`حذف المورد <strong>${e(s.name)}</strong>؟`, { danger: true })) { try { ERP.purchasing.removeSupplier(id); ERP.ui.success('تم'); } catch (err) { ERP.ui.error(err.message); } } } });
      if (canM) $('#sp-add', root).onclick = () => openForm();
      const ag = $('#sp-aging', root); if (ag) ag.onclick = () => ERP.router.go('cheques', { tab: 'aging' }); /* [cheques] */
      $('#sp-print', root).onclick = () => { const l = u.sortBy(ERP.purchasing.suppliers().filter(s => s.balance > 0), 'balance', 'desc'); ERP.print.table({ title: 'تقرير مستحقات الموردين', columns: [{ label: 'الكود' }, { label: 'المورد' }, { label: 'الهاتف' }, { label: 'المستحق', num: true }], rows: l.map(s => [s.code, s.name, s.phone || '', u.fmtNum(s.balance)]), summary: [{ label: 'عدد الموردين', value: l.length }, { label: 'الإجمالي', value: u.fmtMoney(u.sum(l, 'balance')) }] }); };
    },
    onShow(root, params) { refresh(); if (params.id) details(params.id); },
  });
  ERP.bus.on('db:change', u.debounce(ev => { if (table && ERP.router.current() === 'suppliers' && ['suppliers', 'purchases', 'payments'].includes(ev?.collection)) refresh(); }, 250));
})();
